// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeDomainShift(arg1) {
  return window['go']['main']['App']['AnalyzeDomainShift'](arg1);
}

export function AnalyzeDomainShiftCohort(arg1) {
  return window['go']['main']['App']['AnalyzeDomainShiftCohort'](arg1);
}

export function AnalyzeEnergyModel(arg1) {
  return window['go']['main']['App']['AnalyzeEnergyModel'](arg1);
}

export function AnalyzeLULC(arg1) {
  return window['go']['main']['App']['AnalyzeLULC'](arg1);
}

export function AnalyzeSolar(arg1) {
  return window['go']['main']['App']['AnalyzeSolar'](arg1);
}

export function AnalyzeSolarSiting(arg1) {
  return window['go']['main']['App']['AnalyzeSolarSiting'](arg1);
}

export function AnalyzeSolarTerrain(arg1) {
  return window['go']['main']['App']['AnalyzeSolarTerrain'](arg1);
}

export function AnalyzeWater(arg1) {
  return window['go']['main']['App']['AnalyzeWater'](arg1);
}

export function AnalyzeWind(arg1) {
  return window['go']['main']['App']['AnalyzeWind'](arg1);
}

export function BuildCanopyField(arg1) {
  return window['go']['main']['App']['BuildCanopyField'](arg1);
}

export function BuildCanopyFromAOI(arg1) {
  return window['go']['main']['App']['BuildCanopyFromAOI'](arg1);
}

export function BuildCanopyMesh(arg1) {
  return window['go']['main']['App']['BuildCanopyMesh'](arg1);
}

export function BuildManagedEnvironment(arg1) {
  return window['go']['main']['App']['BuildManagedEnvironment'](arg1);
}

export function CancelEnvironmentBuild() {
  return window['go']['main']['App']['CancelEnvironmentBuild']();
}

export function ChooseBackupArchive() {
  return window['go']['main']['App']['ChooseBackupArchive']();
}

export function ClearAvatar() {
  return window['go']['main']['App']['ClearAvatar']();
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function CurrentUser() {
  return window['go']['main']['App']['CurrentUser']();
}

export function DeleteAnalysis(arg1) {
  return window['go']['main']['App']['DeleteAnalysis'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteProjectOverlay(arg1) {
  return window['go']['main']['App']['DeleteProjectOverlay'](arg1);
}

export function DeleteWhiteboard(arg1) {
  return window['go']['main']['App']['DeleteWhiteboard'](arg1);
}

export function ExportBackup() {
  return window['go']['main']['App']['ExportBackup']();
}

export function ExportClassification(arg1) {
  return window['go']['main']['App']['ExportClassification'](arg1);
}

export function ExportOverlayFile(arg1, arg2) {
  return window['go']['main']['App']['ExportOverlayFile'](arg1, arg2);
}

export function ExportResearchPack(arg1, arg2) {
  return window['go']['main']['App']['ExportResearchPack'](arg1, arg2);
}

export function GeocodeSearch(arg1) {
  return window['go']['main']['App']['GeocodeSearch'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBootLogs() {
  return window['go']['main']['App']['GetBootLogs']();
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetWhiteboard(arg1) {
  return window['go']['main']['App']['GetWhiteboard'](arg1);
}

export function InspectEnvironment() {
  return window['go']['main']['App']['InspectEnvironment']();
}

export function InspectPython(arg1) {
  return window['go']['main']['App']['InspectPython'](arg1);
}

export function InspectStorage() {
  return window['go']['main']['App']['InspectStorage']();
}

export function ListDataCube(arg1) {
  return window['go']['main']['App']['ListDataCube'](arg1);
}

export function ListEmbeddedAreas() {
  return window['go']['main']['App']['ListEmbeddedAreas']();
}

export function ListOptionalPackages() {
  return window['go']['main']['App']['ListOptionalPackages']();
}

export function ListProjectOverlays(arg1) {
  return window['go']['main']['App']['ListProjectOverlays'](arg1);
}

export function ListProjectRuns(arg1, arg2) {
  return window['go']['main']['App']['ListProjectRuns'](arg1, arg2);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListRuns(arg1) {
  return window['go']['main']['App']['ListRuns'](arg1);
}

export function ListWhiteboards() {
  return window['go']['main']['App']['ListWhiteboards']();
}

export function LoadAnalysis(arg1) {
  return window['go']['main']['App']['LoadAnalysis'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function ManageOptionalPackage(arg1, arg2) {
  return window['go']['main']['App']['ManageOptionalPackage'](arg1, arg2);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function Predict(arg1) {
  return window['go']['main']['App']['Predict'](arg1);
}

export function PurgeOrphanedRunAssets() {
  return window['go']['main']['App']['PurgeOrphanedRunAssets']();
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function RenameWhiteboard(arg1, arg2) {
  return window['go']['main']['App']['RenameWhiteboard'](arg1, arg2);
}

export function RenderComposite(arg1) {
  return window['go']['main']['App']['RenderComposite'](arg1);
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function RevealMainWindow() {
  return window['go']['main']['App']['RevealMainWindow']();
}

export function RunActivity(arg1) {
  return window['go']['main']['App']['RunActivity'](arg1);
}

export function SavePreferences(arg1) {
  return window['go']['main']['App']['SavePreferences'](arg1);
}

export function SaveProjectOverlay(arg1) {
  return window['go']['main']['App']['SaveProjectOverlay'](arg1);
}

export function SaveWhiteboard(arg1) {
  return window['go']['main']['App']['SaveWhiteboard'](arg1);
}

export function SetAvatar(arg1) {
  return window['go']['main']['App']['SetAvatar'](arg1);
}

export function SetRunProject(arg1, arg2) {
  return window['go']['main']['App']['SetRunProject'](arg1, arg2);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function UpdateProjectAOI(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateProjectAOI'](arg1, arg2, arg3, arg4);
}

export function UpdateProjectRunLabels(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectRunLabels'](arg1, arg2);
}

export function UseInterpreter(arg1) {
  return window['go']['main']['App']['UseInterpreter'](arg1);
}
