// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {store} from '../models';
import {main} from '../models';

export function AnalyzeDomainShift(arg1:backend.DomainShiftRequest):Promise<backend.DomainShiftReport>;

export function AnalyzeDomainShiftCohort(arg1:backend.DomainShiftCohortRequest):Promise<backend.DomainShiftCohort>;

export function AnalyzeEnergyModel(arg1:backend.EnergyModelRequest):Promise<backend.EnergyModelAnalysis>;

export function AnalyzeLULC(arg1:backend.LULCRequest):Promise<backend.LULCAnalysis>;

export function AnalyzeSolar(arg1:backend.SolarRequest):Promise<backend.SolarAnalysis>;

export function AnalyzeSolarSiting(arg1:backend.SolarSitingRequest):Promise<backend.SolarSitingAnalysis>;

export function AnalyzeSolarTerrain(arg1:backend.SolarTerrainRequest):Promise<backend.SolarTerrainAnalysis>;

export function AnalyzeWater(arg1:backend.WaterRequest):Promise<backend.WaterAnalysis>;

export function AnalyzeWind(arg1:backend.WindRequest):Promise<backend.WindAnalysis>;

export function BuildManagedEnvironment(arg1:string):Promise<void>;

export function CancelEnvironmentBuild():Promise<void>;

export function ChooseBackupArchive():Promise<store.RestorePreview>;

export function ClearAvatar():Promise<store.User>;

export function CreateProject(arg1:string,arg2:string):Promise<store.Project>;

export function CurrentUser():Promise<store.User>;

export function DeleteAnalysis(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteProjectOverlay(arg1:string):Promise<void>;

export function DeleteWhiteboard(arg1:string):Promise<void>;

export function ExportBackup():Promise<string>;

export function ExportClassification(arg1:string):Promise<string>;

export function ExportOverlayFile(arg1:string,arg2:string):Promise<string>;

export function ExportResearchPack(arg1:backend.ResearchExportMeta,arg2:backend.PredictResult):Promise<string>;

export function GeocodeSearch(arg1:string):Promise<Array<backend.GeocodeResult>>;

export function GetAppVersion():Promise<string>;

export function GetBootLogs():Promise<Array<string>>;

export function GetPreferences():Promise<store.Preferences>;

export function GetProject(arg1:string):Promise<store.Project>;

export function GetWhiteboard(arg1:string):Promise<store.Whiteboard>;

export function InspectEnvironment():Promise<main.EnvironmentState>;

export function InspectPython(arg1:string):Promise<backend.EnvReport>;

export function InspectStorage():Promise<store.StorageReport>;

export function ListDataCube(arg1:backend.DataCubeRequest):Promise<backend.DataCubeResult>;

export function ListEmbeddedAreas():Promise<Array<backend.Area>>;

export function ListOptionalPackages():Promise<Array<backend.OptionalPackage>>;

export function ListProjectOverlays(arg1:string):Promise<Array<store.ProjectOverlay>>;

export function ListProjectRuns(arg1:string,arg2:number):Promise<Array<store.InferenceRun>>;

export function ListProjects():Promise<Array<store.Project>>;

export function ListRuns(arg1:number):Promise<Array<store.InferenceRun>>;

export function ListWhiteboards():Promise<Array<store.Whiteboard>>;

export function LoadAnalysis(arg1:string):Promise<backend.PredictResult>;

export function Login(arg1:string,arg2:string):Promise<store.User>;

export function Logout():Promise<void>;

export function ManageOptionalPackage(arg1:string,arg2:boolean):Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function Predict(arg1:backend.PredictRequest):Promise<backend.PredictResult>;

export function PurgeOrphanedRunAssets():Promise<store.PurgeResult>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<store.User>;

export function RenameWhiteboard(arg1:string,arg2:string):Promise<void>;

export function RenderComposite(arg1:backend.CompositeRequest):Promise<backend.CompositeResult>;

export function RestoreBackup(arg1:string):Promise<store.RestoreResult>;

export function RevealMainWindow():Promise<void>;

export function RunActivity(arg1:number):Promise<Array<store.ActivityDay>>;

export function SavePreferences(arg1:store.Preferences):Promise<void>;

export function SaveProjectOverlay(arg1:main.SaveProjectOverlayRequest):Promise<store.ProjectOverlay>;

export function SaveWhiteboard(arg1:store.Whiteboard):Promise<store.Whiteboard>;

export function SetAvatar(arg1:string):Promise<store.User>;

export function SetRunProject(arg1:string,arg2:string):Promise<void>;

export function UpdateProfile(arg1:string):Promise<store.User>;

export function UpdateProject(arg1:store.Project):Promise<store.Project>;

export function UpdateProjectAOI(arg1:string,arg2:string,arg3:string,arg4:string):Promise<store.Project>;

export function UpdateProjectRunLabels(arg1:string,arg2:string):Promise<number>;

export function UseInterpreter(arg1:string):Promise<backend.EnvReport>;
