// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {store} from '../models';
import {main} from '../models';

export function AnalyzeLULC(arg1:backend.LULCRequest):Promise<backend.LULCAnalysis>;

export function AnalyzeWater(arg1:backend.WaterRequest):Promise<backend.WaterAnalysis>;

export function ClearAvatar():Promise<store.User>;

export function CreateProject(arg1:string,arg2:string):Promise<store.Project>;

export function CurrentUser():Promise<store.User>;

export function DeleteAnalysis(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteProjectOverlay(arg1:string):Promise<void>;

export function ExportClassification(arg1:string):Promise<string>;

export function ExportOverlayFile(arg1:string,arg2:string):Promise<string>;

export function ExportResearchPack(arg1:backend.ResearchExportMeta,arg2:backend.PredictResult):Promise<string>;

export function GeocodeSearch(arg1:string):Promise<Array<backend.GeocodeResult>>;

export function GetAppVersion():Promise<string>;

export function GetBootLogs():Promise<Array<string>>;

export function GetPreferences():Promise<store.Preferences>;

export function GetProject(arg1:string):Promise<store.Project>;

export function ListDataCube(arg1:backend.DataCubeRequest):Promise<backend.DataCubeResult>;

export function ListEmbeddedAreas():Promise<Array<backend.Area>>;

export function ListProjectOverlays(arg1:string):Promise<Array<store.ProjectOverlay>>;

export function ListProjectRuns(arg1:string,arg2:number):Promise<Array<store.InferenceRun>>;

export function ListProjects():Promise<Array<store.Project>>;

export function ListRuns(arg1:number):Promise<Array<store.InferenceRun>>;

export function LoadAnalysis(arg1:string):Promise<backend.PredictResult>;

export function Login(arg1:string,arg2:string):Promise<store.User>;

export function Logout():Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function Predict(arg1:backend.PredictRequest):Promise<backend.PredictResult>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<store.User>;

export function RenderComposite(arg1:backend.CompositeRequest):Promise<backend.CompositeResult>;

export function RevealMainWindow():Promise<void>;

export function SavePreferences(arg1:store.Preferences):Promise<void>;

export function SaveProjectOverlay(arg1:main.SaveProjectOverlayRequest):Promise<store.ProjectOverlay>;

export function SetAvatar(arg1:string):Promise<store.User>;

export function SetRunProject(arg1:string,arg2:string):Promise<void>;

export function UpdateProfile(arg1:string):Promise<store.User>;

export function UpdateProject(arg1:store.Project):Promise<store.Project>;

export function UpdateProjectAOI(arg1:string,arg2:string,arg3:string,arg4:string):Promise<store.Project>;

export function UpdateProjectRunLabels(arg1:string,arg2:string):Promise<number>;
