// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {analysis} from '../models';
import {store} from '../models';
import {geocode} from '../models';
import {main} from '../models';
import {pyenv} from '../models';

export function AnalyzeDomainShift(arg1:analysis.DomainShiftRequest):Promise<analysis.DomainShiftReport>;

export function AnalyzeDomainShiftCohort(arg1:analysis.DomainShiftCohortRequest):Promise<analysis.DomainShiftCohort>;

export function AnalyzeEnergyModel(arg1:analysis.EnergyModelRequest):Promise<analysis.EnergyModelAnalysis>;

export function AnalyzeFlood(arg1:analysis.FloodRequest):Promise<analysis.FloodAnalysis>;

export function AnalyzeGridCongestion(arg1:analysis.GridCongestionRequest):Promise<analysis.GridCongestionAnalysis>;

export function AnalyzeGridCurtailment(arg1:analysis.GridCurtailmentRequest):Promise<analysis.GridCurtailmentAnalysis>;

export function AnalyzeGridFigure(arg1:analysis.GridFigureRequest):Promise<analysis.GridFigureAnalysis>;

export function AnalyzeLULC(arg1:analysis.LULCRequest):Promise<analysis.LULCAnalysis>;

export function AnalyzeSolar(arg1:analysis.SolarRequest):Promise<analysis.SolarAnalysis>;

export function AnalyzeSolarSiting(arg1:analysis.SolarSitingRequest):Promise<analysis.SolarSitingAnalysis>;

export function AnalyzeSolarTerrain(arg1:analysis.SolarTerrainRequest):Promise<analysis.SolarTerrainAnalysis>;

export function AnalyzeSurfaceModel(arg1:analysis.SurfaceModelRequest):Promise<analysis.SurfaceModel>;

export function AnalyzeWater(arg1:analysis.WaterRequest):Promise<analysis.WaterAnalysis>;

export function AnalyzeWind(arg1:analysis.WindRequest):Promise<analysis.WindAnalysis>;

export function BuildCanopyField(arg1:analysis.CanopyFieldRequest):Promise<analysis.CanopyField>;

export function BuildCanopyFromAOI(arg1:analysis.CanopyFromAOIRequest):Promise<analysis.CanopyFromAOI>;

export function BuildCanopyMesh(arg1:analysis.CanopyMeshRequest):Promise<analysis.CanopyMesh>;

export function BuildManagedEnvironment(arg1:string):Promise<void>;

export function CancelEnvironmentBuild():Promise<void>;

export function ChooseBackupArchive():Promise<store.RestorePreview>;

export function ClearAvatar():Promise<store.User>;

export function CreateArea(arg1:string,arg2:string,arg3:string):Promise<store.Area>;

export function CreateProject(arg1:string,arg2:string):Promise<store.Project>;

export function CurrentUser():Promise<store.User>;

export function DeleteAnalysis(arg1:string):Promise<void>;

export function DeleteArea(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteProjectOverlay(arg1:string):Promise<void>;

export function DeleteStudio(arg1:string):Promise<void>;

export function ExportBackup():Promise<string>;

export function ExportClassification(arg1:string):Promise<string>;

export function ExportOverlayFile(arg1:string,arg2:string):Promise<string>;

export function ExportResearchPack(arg1:analysis.ResearchExportMeta,arg2:analysis.PredictResult):Promise<string>;

export function GeocodeSearch(arg1:string):Promise<Array<geocode.GeocodeResult>>;

export function GetAppVersion():Promise<string>;

export function GetArea(arg1:string):Promise<store.Area>;

export function GetBootLogs():Promise<Array<string>>;

export function GetPreferences():Promise<store.Preferences>;

export function GetProject(arg1:string):Promise<store.Project>;

export function GetStudio(arg1:string):Promise<store.Studio>;

export function GridNetwork(arg1:Array<number>,arg2:number):Promise<analysis.GridNetworkLayer>;

export function GridPlants(arg1:Array<number>,arg2:Array<string>):Promise<analysis.GridPlantsLayer>;

export function InspectEnvironment():Promise<main.EnvironmentState>;

export function InspectGridStore():Promise<analysis.GridStoreReport>;

export function InspectPython(arg1:string):Promise<pyenv.EnvReport>;

export function InspectStorage():Promise<store.StorageReport>;

export function ListAreaRuns(arg1:string,arg2:number):Promise<Array<store.InferenceRun>>;

export function ListAreas(arg1:string):Promise<Array<store.Area>>;

export function ListDataCube(arg1:analysis.DataCubeRequest):Promise<analysis.DataCubeResult>;

export function ListOptionalPackages():Promise<Array<pyenv.OptionalPackage>>;

export function ListProjectOverlays(arg1:string):Promise<Array<store.ProjectOverlay>>;

export function ListProjectRuns(arg1:string,arg2:number):Promise<Array<store.InferenceRun>>;

export function ListProjects():Promise<Array<store.Project>>;

export function ListRuns(arg1:number):Promise<Array<store.InferenceRun>>;

export function ListStudios(arg1:string):Promise<Array<store.Studio>>;

export function LoadAnalysis(arg1:string):Promise<analysis.PredictResult>;

export function Login(arg1:string,arg2:string):Promise<store.User>;

export function Logout():Promise<void>;

export function ManageOptionalPackage(arg1:string,arg2:boolean):Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function Predict(arg1:analysis.PredictRequest):Promise<analysis.PredictResult>;

export function PurgeOrphanedRunAssets():Promise<store.PurgeResult>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<store.User>;

export function RenameStudio(arg1:string,arg2:string):Promise<void>;

export function RenderComposite(arg1:analysis.CompositeRequest):Promise<analysis.CompositeResult>;

export function RestoreBackup(arg1:string):Promise<store.RestoreResult>;

export function RevealMainWindow():Promise<void>;

export function RunActivity(arg1:number):Promise<Array<store.ActivityDay>>;

export function SavePreferences(arg1:store.Preferences):Promise<void>;

export function SaveProjectOverlay(arg1:main.SaveProjectOverlayRequest):Promise<store.ProjectOverlay>;

export function SaveStudio(arg1:store.Studio):Promise<store.Studio>;

export function SetAvatar(arg1:string):Promise<store.User>;

export function SetGridStore(arg1:string):Promise<analysis.GridStoreReport>;

export function SetProjectLastArea(arg1:string,arg2:string):Promise<store.Project>;

export function SetRunProject(arg1:string,arg2:string):Promise<void>;

export function UpdateArea(arg1:store.Area):Promise<store.Area>;

export function UpdateProfile(arg1:string):Promise<store.User>;

export function UpdateProject(arg1:store.Project):Promise<store.Project>;

export function UpdateProjectRunLabels(arg1:string,arg2:string):Promise<number>;

export function UseInterpreter(arg1:string):Promise<pyenv.EnvReport>;
