// Types mirroring the Go backend structs (backend/types.go). The Wails bridge
// also generates models under wailsjs/go/models.ts after `wails dev`; these
// local definitions keep the frontend readable and self-contained.

export interface Bounds {
  lon_min: number
  lat_min: number
  lon_max: number
  lat_max: number
}

export interface GeoJSONGeometry {
  type: string
  coordinates: number[][][]
}

export interface Area {
  id: string
  label: string
  kml_name: string
  approximate: boolean
  centroid: number[]
  bounds: Bounds
  mapbiomas: string
  geometry: GeoJSONGeometry
}

export type ModelKind = "spectral" | "prithvi" | "temporal_transformer"

export interface PredictRequest {
  area_id: string
  polygon_geojson: GeoJSONGeometry | null
  start: string
  end: string
  max_cloud: number
  monthly_best: boolean
  tiles: string[]
  mode: "single" | "temporal"
  model_kind: ModelKind
  prithvi_mode: "pixel" | "patch"
  /** Attach the saved run to this project when set. */
  project_id?: string
  /** Display name for the AOI (custom rename or example label). */
  label?: string
  /** Inference run title (run-…). Generated by backend if omitted. */
  run_label?: string
}

export interface ClassStat {
  class_id: number
  name: string
  color: string
  pixels: number
  pct: number
  area_ha: number
}

export interface TemporalPoint {
  date: string
  n_dates_stack: number
  soja_ndvi_mean: number | null
  soja_retention_pct: number | null
  dominant: string | null
}

export interface VISeriesPoint {
  date: string
  ndvi_mean: number
  ndvi_std: number
  evi_mean: number
  evi_std: number
  savi_mean: number
  savi_std: number
}

export interface PhenologyMetrics {
  sos_doy: number | null
  pos_doy: number | null
  eos_doy: number | null
  los_days: number | null
  peak: number | null
  base: number | null
  amplitude: number | null
}

export interface PhenologyStatePoint {
  date: string
  state: number
  state_name: string
  color: string
  ndvi_mean: number | null
}

export interface LULCClassRow {
  class_id: number
  name: string
  color: string
  group: string
  pixels: number
  pct: number
  area_ha: number
}

export interface LULCGroupRow {
  group: string
  color: string
  pct: number
  area_ha: number
}

export interface LULCMetrics {
  area_ha: number
  n_pixels: number
  n_classes: number
  shannon_h: number
  pielou_j: number
  dominant_class: string
  dominant_pct: number
  soja_pct: number
  outras_lav_pct: number
  agricola_pct: number
}

export interface LULCCompareRow {
  class_id: number
  name: string
  color: string
  pct_ref: number
  pct_pred: number
  /** 10 m pixels of this class in the reference, on the classification grid. */
  pixels_ref?: number
  /**
   * Distinct native 30 m MapBiomas cells behind those pixels. This is the
   * number of independent label observations; the pixel count is about nine
   * times larger and is not a sample size.
   */
  n_reference_cells?: number
}

export interface LULCAnalysis {
  year: number
  source: string
  map_uri?: string
  extent?: Bounds
  metrics: LULCMetrics
  composition: LULCClassRow[]
  groups: LULCGroupRow[]
  pred_vs_ref: LULCCompareRow[]
  /** Valid 10 m pixels shared by both maps. */
  compare_pixels?: number
  /** Distinct native reference cells behind them; the comparison sample size. */
  compare_reference_cells?: number
}

export interface LULCRequest {
  area_id: string
  polygon_geojson?: GeoJSONGeometry | null
  mapbiomas_path?: string
}

export interface PredictResult {
  extent: Bounds
  overlay_uri: string
  confidence_uri: string
  ndvi_mean_uri: string
  true_color_uri: string
  reference_uri: string
  raster_tif: string
  mean_confidence: number
  n_dates: number
  date_range: string[]
  class_stats: ClassStat[]
  temporal: TemporalPoint[]
  vi_series: VISeriesPoint[]
  phenology: PhenologyMetrics
  phenology_states: PhenologyStatePoint[]
  lulc?: LULCAnalysis | null
  /** Attached when a surface-water run was made over the same AOI. */
  water?: WaterAnalysis | null
}

export interface ProgressEvent {
  progress: number
  msg: string
}

export interface GeocodeResult {
  display_name: string
  lat: number
  lon: number
  bounding_box: number[]
}

export interface User {
  id: string
  email: string
  display_name: string
  avatar_path?: string
  avatar_uri?: string
  created_at: string
  updated_at: string
}

export interface Preferences {
  user_id: string
  default_model: string
  overlay_opacity: number
  theme: string
  extras_json?: string
}

/** How vertical left-dock tabs behave (stored in extras_json.left_dock_tabs). */
export type LeftDockTabsMode = "retracted_only" | "always"

export interface InferenceRun {
  id: string
  user_id: string
  created_at: string
  model_kind: string
  period_start: string
  period_end: string
  polygon_geojson: string
  status: string
  summary: string
  result_json?: string
  overlay_relpath?: string
  assets_relpath?: string
  n_dates: number
  label?: string
  project_id?: string
  /** "classification" or "water"; empty on rows written before the column. */
  kind?: string
}

export interface Project {
  id: string
  user_id: string
  name: string
  notes?: string
  created_at: string
  updated_at: string
  polygon_geojson?: string
  area_id?: string
  label?: string
  run_count?: number
  overlay_count?: number
}

export interface ProjectOverlay {
  id: string
  project_id: string
  kind: string
  title: string
  meta_json?: string
  png_relpath?: string
  tif_relpath?: string
  created_at: string
  overlay_uri?: string
  raster_tif?: string
}

export interface SaveProjectOverlayRequest {
  project_id: string
  kind: string
  title: string
  meta_json: string
  overlay_uri: string
  raster_tif?: string
}

export interface DataCubeRequest {
  area_id: string
  polygon_geojson: GeoJSONGeometry | null
  start: string
  end: string
  max_cloud: number
  monthly_best: boolean
  tiles: string[]
}

export interface DataCubeScene {
  id: string
  date: string
  cloud_cover: number
  tile: string
  satellite: string
  preview_uri?: string
}

export interface DataCubeResult {
  n_scenes: number
  scenes: DataCubeScene[]
  date_range: string[]
  monthly_best: boolean
  max_cloud: number
}

export type CompositeKind = "rgb" | "index"
export type CompositeIndex = "ndvi" | "ndwi" | "ndmi" | "evi"

export interface CompositeRequest {
  area_id: string
  polygon_geojson: GeoJSONGeometry | null
  start: string
  end: string
  max_cloud: number
  monthly_best: boolean
  tiles: string[]
  scene_id: string
  kind: CompositeKind
  bands?: string[]
  index?: CompositeIndex
  stretch_pct?: number[]
}

export interface CompositeResult {
  extent: Bounds
  overlay_uri: string
  raster_tif?: string
  meta?: Record<string, unknown>
}

export interface CompositionOverlay {
  /** Client session id — stable key for the overlay gallery. */
  id: string
  overlay_uri: string
  extent: Bounds
  opacity: number
  /** Short telemetry line, e.g. "Agriculture · B11-B08-B02" */
  label?: string
  /** Display name, e.g. "Agriculture" or "NDVI" */
  title?: string
  description?: string
  kind?: CompositeKind
  bands?: [string, string, string]
  index?: CompositeIndex
  presetId?: string
  /** Scene acquisition date captured at apply time. */
  sceneDate?: string
  /** Local GeoTIFF path for export (when available). */
  raster_tif?: string
}

export type WaterIndex = "NDWI" | "MNDWI" | "AWEI"

export interface WaterDate {
  date: string
  scene_id: string
  cloud_cover: number
  /**
   * AOI pixels actually observed on this date. Water fractions are a percentage
   * of this, not of the whole AOI, so a partly clouded date is not read as dry.
   */
  observed_pixels: number
  threshold_fixed: number
  threshold_otsu: number
  /** The Otsu value hit an empirical bound and is a bound, not an estimate. */
  threshold_clipped: boolean
  /** Too few observations to threshold at all. */
  threshold_degenerate: boolean
  water_fraction_pct: number
  water_fraction_otsu_pct: number
  water_pixels: number
  area_ha: number
}

export interface WaterAnalysis {
  index: WaterIndex
  threshold_method: string
  threshold_fixed: number
  otsu_clip: number[]
  n_dates: number
  date_range: string[]
  aoi_pixels: number
  aoi_area_ha: number
  series: WaterDate[]
  peak_date: string
  peak_water_fraction_pct: number
  /** Water on some dates but not most: the flood signal rather than a pond. */
  ephemeral_pixels: number
  ephemeral_area_ha: number
  persistent_pixels: number
  persistent_area_ha: number
  mean_anomaly: number
  /** Occurrence raster as a data URI, coloured on a fixed 0 to 1 scale. */
  occurrence_uri: string
  extent: Bounds
}

export interface WaterRequest {
  area_id: string
  polygon_geojson: GeoJSONGeometry | null
  start: string
  end: string
  max_cloud: number
  monthly_best: boolean
  index: WaterIndex
  label?: string
  run_label?: string
  project_id?: string
}

export interface SolarMonth {
  month: number
  ghi: number | null
  dni: number | null
  dhi: number | null
  kt: number | null
}

export interface SolarAnalysis {
  lon: number
  lat: number
  resource: {
    ghi_annual_kwh_m2: number
    ghi_std: number
    ghi_cv_pct: number
    ghi_p10: number
    ghi_p90: number
    n_years: number
    trend_per_year: number
    trend_p_value: number
    clear_sky_index: number | null
    monthly: SolarMonth[]
  }
  geometry: {
    optimal_tilt_deg: number
    optimal_poa_kwh_m2_year: number
    surface_azimuth_deg: number
    gain_over_horizontal_pct: number
    tilt_tolerance: { deviation_deg: number; loss_pct: number }[]
  }
  pv: {
    specific_yield_kwh_kwp_year: number
    /** The ratio applied to produce the yield. */
    performance_ratio: number
    /** "reference" or "user". */
    performance_ratio_source: string
    /**
     * What the chain models. Runs high because soiling, inter-row shading,
     * degradation, availability and cabling are not modelled, so it is shown
     * for comparison rather than applied.
     */
    performance_ratio_modelled: number
    capacity_factor_pct: number
    hourly_years: number
  }
  /** The grid the figures resolve on. Always shown beside them. */
  grid_note: string
}

export interface SolarRequest {
  area_id: string
  polygon_geojson: GeoJSONGeometry | null
  climatology_years: number
  hourly_years: number
  surface_azimuth: number
  performance_ratio?: number | null
}

export interface SolarTerrainAnalysis {
  poa_min: number
  poa_max: number
  poa_mean: number
  poa_std_pct: number
  slope_mean_deg: number
  slope_max_deg: number
  pixels: number
  hourly_years: number
  dem_source: string
  season: string
  unit: string
  /** Stretched between its own 2nd and 98th percentiles; the range is above. */
  overlay_uri: string
  raster_tif: string
  extent: Bounds
}

export interface SolarTerrainRequest {
  area_id: string
  polygon_geojson: GeoJSONGeometry | null
  hourly_years: number
  /** annual, winter, summer, winter_crop, or anisotropy (winter/summer). */
  season: SolarSeason
}

export type SolarSeason =
  | "annual"
  | "winter"
  | "summer"
  | "winter_crop"
  | "anisotropy"

export interface SolarSitingClass {
  code: number
  name: string
  color: string
  pixels: number
  area_ha: number
  pct: number
}

export interface SolarSitingAnalysis {
  classes: SolarSitingClass[]
  /** Never summed with the cropland class: the trade-off must stay visible. */
  suitable_no_conflict_ha: number
  suitable_cropland_ha: number
  pixel_area_ha: number
  thresholds: {
    slope_acceptable_deg: number
    slope_restrictive_deg: number
    excluded_cover: number[]
    cropland_cover: number[]
    note: string
  }
  dem_source: string
  overlay_uri: string
  raster_tif: string
  extent: Bounds
}

export interface SolarSitingRequest {
  area_id: string
  polygon_geojson: GeoJSONGeometry | null
  slope_acceptable_deg: number
  slope_restrictive_deg: number
}
