// Types mirroring the Go backend structs (backend/types.go). The Wails bridge
// also generates models under wailsjs/go/models.ts after `wails dev`; these
// local definitions keep the frontend readable and self-contained.
//
// Being a hand copy, this file can drift from the structs it mirrors without
// anything failing. scripts/check-types.ts compares the JSON field names of
// every struct that has a same-named interface here and exits non-zero when
// the two sets differ; it says in its own header what it does not compare.

import type { PaletteName } from "./palettes"

export interface Bounds {
  lon_min: number
  lat_min: number
  lon_max: number
  lat_max: number
}

export interface GeoJSONGeometry {
  type: string
  coordinates: number[][][]
}

export interface Area {
  id: string
  label: string
  kml_name: string
  approximate: boolean
  centroid: number[]
  bounds: Bounds
  mapbiomas: string
  geometry: GeoJSONGeometry
}

export type ModelKind = "spectral" | "prithvi" | "temporal_transformer"

export interface PredictRequest {
  area_id: string
  polygon_geojson: GeoJSONGeometry | null
  start: string
  end: string
  max_cloud: number
  monthly_best: boolean
  tiles: string[]
  mode: "single" | "temporal"
  model_kind: ModelKind
  prithvi_mode: "pixel" | "patch"
  /** Attach the saved run to this project when set. */
  project_id?: string
  /** Display name for the AOI (custom rename or example label). */
  label?: string
  /** Inference run title (run-…). Generated by backend if omitted. */
  run_label?: string
  /** The catalogued AOI this run is of, so the board can link the two. */
  aoi_id?: string
}

export interface ClassStat {
  class_id: number
  name: string
  color: string
  pixels: number
  pct: number
  area_ha: number
}

/** One band of a reference spectrum from a spectral library. */
export interface LibraryBand {
  band: string
  wavelength_nm: number
  reflectance: number
}

/**
 * The material a comparison is made against.
 *
 * `level` decides how the result may be read. A leaf-level reference against a
 * canopy pixel cannot identify a material however small the angle, because the
 * two are not measurements of the same thing.
 */
export interface LibraryReference {
  material: string
  source: string
  package_id: string
  n_spectra: number
  level: string
  note: string
  bands: LibraryBand[]
}

export interface LibraryClassBand {
  band: string
  wavelength_nm: number
  canopy: number
  leaf: number
  /** Canopy over leaf. Constant would be brightness, which the angle ignores. */
  ratio: number | null
  unit_canopy: number | null
  unit_leaf: number | null
}

export interface LibraryClass {
  class_id: number
  name: string
  color: string
  angle_rad: number
  bands: LibraryClassBand[]
}

/**
 * The cross-reference against a spectral library, and its limit.
 *
 * Classes are ordered by angle, closest first, and the ordering is the point:
 * the class named Soybean is not the one closest to the soybean reference. A
 * small angle here means CONSISTENCY and never identification.
 */
export interface LibraryLimit {
  reference: LibraryReference
  scene_date: string
  classes: LibraryClass[]
}

/** One band, for one predicted class, on one acquisition. */
export interface ClassSpectrumPoint {
  class_id: number
  name: string
  color: string
  band: string
  wavelength_nm: number
  n_pixels: number
  mean: number
  sd: number
  p05: number
  p95: number
}

/**
 * The measured spectral response per predicted class.
 *
 * `scene_date` is not provenance trim. The classification spans the period and
 * the reflectance is one acquisition, so a reader who takes the curve for a
 * seasonal mean is reading something this payload does not contain.
 */
export interface ClassSpectra {
  scene_date: string
  scene_id?: string
  n_scenes: number
  convention: string
  bands: string[]
  points: ClassSpectrumPoint[]
}

export interface TemporalPoint {
  date: string
  n_dates_stack: number
  soja_ndvi_mean: number | null
  soja_retention_pct: number | null
  dominant: string | null
}

export interface VISeriesPoint {
  date: string
  ndvi_mean: number
  ndvi_std: number
  evi_mean: number
  evi_std: number
  savi_mean: number
  savi_std: number
}

export interface PhenologyMetrics {
  sos_doy: number | null
  pos_doy: number | null
  eos_doy: number | null
  los_days: number | null
  peak: number | null
  base: number | null
  amplitude: number | null
}

export interface PhenologyStatePoint {
  date: string
  state: number
  state_name: string
  color: string
  ndvi_mean: number | null
}

export interface LULCClassRow {
  class_id: number
  name: string
  color: string
  group: string
  pixels: number
  pct: number
  area_ha: number
}

export interface LULCGroupRow {
  group: string
  color: string
  pct: number
  area_ha: number
}

export interface LULCMetrics {
  area_ha: number
  n_pixels: number
  n_classes: number
  shannon_h: number
  pielou_j: number
  dominant_class: string
  dominant_pct: number
  soja_pct: number
  outras_lav_pct: number
  agricola_pct: number
}

export interface LULCCompareRow {
  class_id: number
  name: string
  color: string
  pct_ref: number
  pct_pred: number
  /** 10 m pixels of this class in the reference, on the classification grid. */
  pixels_ref?: number
  /**
   * Distinct native 30 m MapBiomas cells behind those pixels. This is the
   * number of independent label observations; the pixel count is about nine
   * times larger and is not a sample size.
   */
  n_reference_cells?: number
}

/** One class's producer's and user's accuracy, each with a 95% interval. */
export interface LULCClassAccuracy {
  class_id: number
  name: string
  color: string
  /** Of the reference cells of this class, the share the classifier found. */
  producers_pct: number | null
  producers_ci?: [number, number]
  /** Of the cells called this class, the share that really are. */
  users_pct: number | null
  users_ci?: [number, number]
  n_reference: number
  n_predicted: number
}

/**
 * Agreement against the reference — what the composition comparison cannot say.
 *
 * Two maps holding identical proportions of every class can disagree on every
 * cell, so the composition rows and this measure different things. Computed
 * over the reference's native 30 m cells, not the 10 m pixels resampled from
 * them, because nine pixels carrying one label are one observation.
 */
export interface LULCAgreement {
  n_reference_cells: number
  overall_pct: number
  overall_ci: [number, number]
  /** Pontius & Millones (2011): different amounts vs. different places. */
  quantity_disagreement_pct: number
  allocation_disagreement_pct: number
  per_class: LULCClassAccuracy[]
  /** Reference cells whose class the classifier has no label for. */
  n_outside_legend: number
  /**
   * Rows are the classification, columns the reference.
   *
   * `agreement_against_reference` fills `matrix[pred][ref]` and derives
   * producer's accuracy from the column totals. Read the other way round it
   * still looks like a confusion matrix and reports commission as omission,
   * which is why the orientation is stated here and not left to the reader.
   */
  matrix: number[][]
  matrix_classes: number[]
  /** Absent where no block held enough reference cells to carry a figure. */
  blocks?: LULCAgreementBlocks | null
}

/**
 * Agreement over a fixed grid of spatial blocks.
 *
 * `overall_pct` cannot tell a classifier that is uniformly mediocre from one
 * that is accurate everywhere but a corner, and the two call for different
 * work. Descriptive rather than inferential: the blocks are a grid over the
 * raster's extent, not a sampling design.
 */
export interface LULCAgreementBlocks {
  rows: number
  cols: number
  /** Reference cells a block needs before its percentage is reported. */
  min_cells: number
  cells: LULCAgreementBlock[]
  n_measured: number
  median_pct: number
  iqr_pct: number
  min_pct: number
  max_pct: number
}

export interface LULCAgreementBlock {
  row: number
  col: number
  n_reference_cells: number
  /** Null below `min_cells`: arithmetic rather than a measurement. */
  overall_pct: number | null
}

export interface LULCAnalysis {
  year: number
  source: string
  map_uri?: string
  extent?: Bounds
  metrics: LULCMetrics
  composition: LULCClassRow[]
  groups: LULCGroupRow[]
  pred_vs_ref: LULCCompareRow[]
  /** Valid 10 m pixels shared by both maps. */
  compare_pixels?: number
  /** Distinct native reference cells behind them; the comparison sample size. */
  compare_reference_cells?: number
  /** Absent when the reference cell mapping was unavailable. */
  agreement?: LULCAgreement
}

export interface LULCRequest {
  area_id: string
  polygon_geojson?: GeoJSONGeometry | null
  mapbiomas_path?: string
}

export interface PredictResult {
  /**
   * The saved run this result became, when one was saved.
   *
   * Set by the backend after persisting, so it is absent from the stored copy
   * of a run's own result. Compositions made while this result is on screen
   * attach to it.
   */
  run_id?: string
  extent: Bounds
  overlay_uri: string
  confidence_uri: string
  ndvi_mean_uri: string
  true_color_uri: string
  reference_uri: string
  raster_tif: string
  /**
   * Mean of max(predict_proba) over classified pixels.
   *
   * Ensemble vote share, not a calibrated probability of being correct:
   * Random Forest vote fractions are biased toward the middle of the range
   * (Niculescu-Mizil & Caruana 2005). Read it with confidence_floor.
   */
  mean_confidence: number
  /** 1/K for a K-class model; the value mean_confidence cannot go below. */
  confidence_floor?: number
  n_dates: number
  // Go marshals a nil slice as null, and a run that produced no classification
  // -- a water or solar run, which needs no scene -- leaves every one of these
  // nil. Declared nullable so each read has to be guarded; taken as guaranteed,
  // one of them blanked the whole application.
  date_range: string[] | null
  /**
   * The side of one predicted pixel on the ground, in metres, off the grid the
   * run was made on. Absent on runs saved before it was carried.
   */
  pixel_size_m?: number
  class_stats: ClassStat[] | null
  /**
   * Absent on older runs, on the non-spectral model paths, and when the scene
   * behind the classification could not be re-read for its bands.
   */
  class_spectra?: ClassSpectra | null
  /** The same spectra measured against a spectral library. */
  library_limit?: LibraryLimit | null
  temporal: TemporalPoint[] | null
  vi_series: VISeriesPoint[] | null
  /**
   * The same dates averaged over CROP PIXELS ONLY, beside the AOI-wide series
   * rather than in place of it.
   *
   * The two can differ in length -- a date whose crop pixels were entirely
   * cloud-obscured leaves this series and stays in the other -- so they must be
   * read by date and never zipped by index. Absent when the AOI carries no
   * cropland, which is a statement and not a failure. Anything inverting an
   * index to leaf area should prefer this one: an area mean over mixed cover is
   * not the crop's index.
   */
  vi_series_crop?: VISeriesPoint[]
  /** The crop share of the AOI, in percent; the denominator for the series above. */
  crop_pixel_pct?: number
  phenology: PhenologyMetrics
  phenology_states: PhenologyStatePoint[] | null
  lulc?: LULCAnalysis | null
  /** Attached when a surface-water run was made over the same AOI. */
  water?: WaterAnalysis | null
  /** Same, for the solar products, which need no scene at all. */
  solar?: SolarAnalysis | null
  solar_terrain?: SolarTerrainAnalysis | null
  solar_siting?: SolarSitingAnalysis | null
  energy_model?: EnergyModelAnalysis | null
  /**
   * A wind screening. Filed under its own run kind, not under solar: the two
   * answer different questions and their capacity factors are not comparable.
   */
  wind?: WindAnalysis | null
  /**
   * A HAND flood envelope: the extent together with the disagreement between
   * the DEM products it can be derived from. Never one product's mask alone --
   * the study this ports found the mask is not reproducible across products,
   * so a lone extent is a shape some DEM chose and the reader is never shown
   * the choice.
   */
  flood?: FloodAnalysis | null
  /**
   * Compact spectral / NDVI fingerprint cached at classify time for
   * domain-shift diagnostics. Absent on older runs and non-classify products.
   */
  domain_fingerprint?: DomainFingerprint | null
}

/** Fixed-edge histogram (NDVI by default). */
export interface DomainHistogram {
  edges: number[]
  counts: number[]
  probs: number[]
}

export interface DomainRedNIR {
  red_mean: number
  nir_mean: number
}

/** Per-run domain summary used by AnalyzeDomainShift. */
export interface DomainFingerprint {
  space: string
  n_features: number
  n_pixels: number
  n_sample: number
  mean: number[]
  var: number[]
  /**
   * In training standard deviations, from the model's own scaler.
   *
   * These decide whether a comparison can be standardised at all. Their
   * absence is what makes the sidecar refuse, and an unstandardised distance
   * is dominated by acquisition-index features rather than by reflectance.
   */
  z_mean?: number[] | null
  z_var?: number[] | null
  feature_names?: string[] | null
  feature_importances?: number[] | null
  ndvi_hist?: DomainHistogram | null
  red_nir?: DomainRedNIR | null
  sample?: number[][] | null
}

/**
 * The kernel two-sample statistic, with what it needs to be read.
 *
 * Not a scalar: MMD is not comparable across bandwidths, so the gamma the
 * median heuristic chose travels with it, as do the sample sizes.
 */
export interface DomainShiftMMD {
  mmd2?: number | null
  gamma?: number | null
  n_a: number
  n_b: number
}

/** One row of the per-feature displacement table. */
export interface DomainFeatureShift {
  feature: string
  z_a: number
  z_b: number
  /** Displacement in training standard deviations. */
  gap_sd: number
  /** Impurity importance from the fitted forest; null for other spaces. */
  importance?: number | null
  /** gap_sd weighted by importance: movement the model actually reads. */
  weighted: number
}

export interface DomainShiftPoint {
  x: number
  y: number
  domain: string
}

export interface DomainShiftProjection {
  method: string
  points: DomainShiftPoint[]
  /**
   * "standardised" or "raw".
   *
   * The axes carry no units either way, but the two are different pictures: on
   * raw features the geometry is set by the acquisition indices, which span
   * 0..21 against reflectances near 0.1.
   */
  space?: string
}

/** One class's precision, recall and F1, from the agreement matrix. */
export interface DomainShiftClassF1 {
  index: number
  /** Null only when the matrix arrived without its axis order. */
  class_id?: number | null
  precision?: number | null
  recall?: number | null
  f1?: number | null
}

export interface DomainShiftAgreementBlock {
  label: string
  overall_pct?: number | null
  n_outside_legend: number
  outside_legend_pct?: number | null
  quantity_disagreement_pct?: number | null
  allocation_disagreement_pct?: number | null
  macro_f1?: number | null
  /**
   * Per-class precision, recall and F1.
   *
   * A macro average says the model got worse; only these say which class. The
   * sidecar has emitted them all along and the Go struct declared no field, so
   * they were dropped at the unmarshal boundary.
   */
  per_class_f1?: DomainShiftClassF1[] | null
}

/**
 * One target measured against the source.
 *
 * Mirrors `DomainShiftReport` minus the histograms, the projection and the
 * feature-shift table: those are per-pair readings and a cohort consumes none
 * of them. A reader who wants them opens the pair.
 */
export interface DomainShiftCohortRow {
  id: string
  label: string
  space_a?: string
  space_b?: string
  kl_ndvi?: number | null
  kl_ndvi_a_to_b?: number | null
  kl_ndvi_b_to_a?: number | null
  same_space: boolean
  standardised: boolean
  cva_magnitude?: number | null
  cva_magnitude_sd?: number | null
  cva_angle_red_nir_deg?: number | null
  mmd_rbf?: DomainShiftMMD | null
  /**
   * Whether this row may sit on the same axis as the others.
   *
   * The two qualifiers resolved to the question the view asks. A row that
   * cannot is not a low score — it is a distance in other units, and plotting
   * it beside the rest is the unqualified comparison the qualifiers exist to
   * prevent.
   */
  comparable: boolean
  agreement_a?: DomainShiftAgreementBlock | null
  agreement_b?: DomainShiftAgreementBlock | null
}

export interface DomainShiftCohortSource {
  id: string
  label: string
  space?: string
  agreement?: DomainShiftAgreementBlock | null
}

/** One source against N targets: the star the transferability question has. */
export interface DomainShiftCohort {
  source: DomainShiftCohortSource
  targets: DomainShiftCohortRow[]
}

/** Diagnosis payload from two fingerprints (KL / CVA / MMD / F1). */
export interface DomainShiftReport {
  space_a?: string
  space_b?: string
  kl_ndvi?: number | null
  kl_ndvi_a_to_b?: number | null
  kl_ndvi_b_to_a?: number | null
  /**
   * Whether the two fingerprints describe the same feature space, and whether
   * both carried the moments needed to standardise. Every distance in this
   * report is unqualified without them.
   */
  same_space?: boolean
  standardised?: boolean
  cva_magnitude?: number | null
  /** The figure to read: the raw magnitude is dominated by index features. */
  cva_magnitude_sd?: number | null
  cva_angle_red_nir_deg?: number | null
  mmd_rbf?: DomainShiftMMD | null
  /** Where the shift is, by feature, in training standard deviations. */
  feature_shift?: DomainFeatureShift[] | null
  ndvi_hist_a?: DomainHistogram | null
  ndvi_hist_b?: DomainHistogram | null
  agreement_a?: DomainShiftAgreementBlock | null
  agreement_b?: DomainShiftAgreementBlock | null
  projection?: DomainShiftProjection | null
}

export interface ProgressEvent {
  progress: number
  msg: string
}

export interface GeocodeResult {
  display_name: string
  lat: number
  lon: number
  bounding_box: number[]
}

export interface User {
  id: string
  email: string
  display_name: string
  avatar_path?: string
  avatar_uri?: string
  created_at: string
  updated_at: string
}

export interface Preferences {
  user_id: string
  default_model: string
  overlay_opacity: number
  theme: string
  extras_json?: string
}

/** How vertical left-dock tabs behave (stored in extras_json.left_dock_tabs). */
export type LeftDockTabsMode = "retracted_only" | "always"

/**
 * Which map layout is in use (stored in extras_json.layout_mode).
 *
 * `docked` names what it is -- the navigation column plus a panel docked to a
 * column beside it -- rather than "default" or "classic", either of which
 * becomes a lie the day the other one wins.
 */
export type LayoutMode = "docked" | "workspace"

/**
 * Whether a session opens with the studio already up
 * (stored in extras_json.start_surface).
 *
 * IT IS A BOOLEAN WEARING TWO NAMES. The studio opens over the map and closes
 * back onto it -- the title bar toggles it at any moment -- so this decides
 * whether it is up at the start and nothing else. It was once described as
 * choosing between two surfaces, and describing it that way is what taught
 * readers there were two applications.
 *
 * The stored strings stay as they are. They are a preference people already
 * have, and rewriting the values to match a better name would silently reset
 * every one of them; `store.go` makes the same argument for the database file
 * that kept its old name through the application's rename.
 *
 * A preference and not a restored state. The studio's open flag is deliberately
 * local to the map screen -- see the note on `board` in MapScreen, which argues
 * that coming back to the map should give the map rather than a board left open
 * twenty minutes ago. This says where a SESSION begins, which is a different
 * question and the only one a reader can answer in advance.
 */
export type StartSurface = "explorer" | "studio"

export interface InferenceRun {
  id: string
  user_id: string
  created_at: string
  model_kind: string
  period_start: string
  period_end: string
  polygon_geojson: string
  status: string
  summary: string
  result_json?: string
  overlay_relpath?: string
  assets_relpath?: string
  n_dates: number
  label?: string
  project_id?: string
  /** "classification" or "water"; empty on rows written before the column. */
  kind?: string
  /**
   * The catalogued area this run was made over, when there was one.
   *
   * The polygon says WHERE the run was made; this says which area it is OF.
   * The board reads it to keep a drawing and the runs over it as one subject
   * instead of one outline per drawing plus one per run. Absent for example
   * areas, for shapes never catalogued, and on runs written before the column
   * existed -- those resolve by geometry instead.
   */
  aoi_id?: string
}

export interface Project {
  id: string
  user_id: string
  name: string
  notes?: string
  created_at: string
  updated_at: string
  polygon_geojson?: string
  area_id?: string
  label?: string
  run_count?: number
  overlay_count?: number
}

export interface ProjectOverlay {
  id: string
  project_id: string
  /**
   * The run on screen when this composition was made.
   *
   * Empty for one made with no run open, and for every row written before the
   * column existed. Empty means "belongs to the project", so those are scoped
   * by their recorded extent instead.
   */
  run_id?: string
  kind: string
  title: string
  meta_json?: string
  png_relpath?: string
  tif_relpath?: string
  created_at: string
  overlay_uri?: string
  raster_tif?: string
}

export interface SaveProjectOverlayRequest {
  /** The run on screen when the composition was made, when there was one. */
  run_id?: string
  project_id: string
  kind: string
  title: string
  meta_json: string
  overlay_uri: string
  raster_tif?: string
}

export interface DataCubeRequest {
  area_id: string
  polygon_geojson: GeoJSONGeometry | null
  start: string
  end: string
  max_cloud: number
  monthly_best: boolean
  tiles: string[]
}

export interface DataCubeScene {
  id: string
  date: string
  cloud_cover: number
  tile: string
  satellite: string
  preview_uri?: string
}

export interface DataCubeResult {
  n_scenes: number
  scenes: DataCubeScene[]
  date_range: string[]
  monthly_best: boolean
  max_cloud: number
}

export type CompositeKind = "rgb" | "index"
export type CompositeIndex = "ndvi" | "ndwi" | "ndmi" | "evi"

export interface CompositeRequest {
  area_id: string
  polygon_geojson: GeoJSONGeometry | null
  start: string
  end: string
  max_cloud: number
  monthly_best: boolean
  tiles: string[]
  scene_id: string
  kind: CompositeKind
  bands?: string[]
  index?: CompositeIndex
  stretch_pct?: number[]
}

export interface CompositeResult {
  extent: Bounds
  overlay_uri: string
  raster_tif?: string
  meta?: Record<string, unknown>
}

export interface CompositionOverlay {
  /** Client session id — stable key for the overlay gallery. */
  id: string
  overlay_uri: string
  extent: Bounds
  opacity: number
  /** Short telemetry line, e.g. "Agriculture · B11-B08-B02" */
  label?: string
  /** Display name, e.g. "Agriculture" or "NDVI" */
  title?: string
  description?: string
  kind?: CompositeKind
  bands?: [string, string, string]
  index?: CompositeIndex
  presetId?: string
  /** Scene acquisition date captured at apply time. */
  sceneDate?: string
  /** Local GeoTIFF path for export (when available). */
  raster_tif?: string
  /** The run this was made under; empty for a project-level composition. */
  runId?: string
}

export type WaterIndex = "NDWI" | "MNDWI" | "AWEI"

export interface WaterDate {
  date: string
  scene_id: string
  cloud_cover: number
  /**
   * AOI pixels actually observed on this date. Water fractions are a percentage
   * of this, not of the whole AOI, so a partly clouded date is not read as dry.
   */
  observed_pixels: number
  threshold_fixed: number
  threshold_otsu: number
  /** The Otsu value hit an empirical bound and is a bound, not an estimate. */
  threshold_clipped: boolean
  /** Too few observations to threshold at all. */
  threshold_degenerate: boolean
  water_fraction_pct: number
  water_fraction_otsu_pct: number
  water_pixels: number
  area_ha: number
}

export interface WaterAnalysis {
  /**
   * The row this run was recorded as, or absent where it was not recorded.
   *
   * The Go side withdraws its claim to have saved by returning nothing, so the
   * absence of this is the withdrawal. Anything telling the reader the run was
   * saved has to read it.
   */
  run_id?: string
  index: WaterIndex
  threshold_method: string
  threshold_fixed: number
  otsu_clip: number[]
  n_dates: number
  date_range: string[]
  aoi_pixels: number
  aoi_area_ha: number
  series: WaterDate[]
  peak_date: string
  peak_water_fraction_pct: number
  /** Water on some dates but not most: the flood signal rather than a pond. */
  ephemeral_pixels: number
  ephemeral_area_ha: number
  persistent_pixels: number
  persistent_area_ha: number
  mean_anomaly: number
  /** Occurrence raster as a data URI, coloured on a fixed 0 to 1 scale. */
  occurrence_uri: string
  extent: Bounds
}

export interface WaterRequest {
  area_id: string
  polygon_geojson: GeoJSONGeometry | null
  start: string
  end: string
  max_cloud: number
  monthly_best: boolean
  index: WaterIndex
  label?: string
  run_label?: string
  project_id?: string
  /** The catalogued AOI this run is of, so the board can link the two. */
  aoi_id?: string
}

export interface SolarMonth {
  month: number
  ghi: number | null
  dni: number | null
  dhi: number | null
  kt: number | null
}

export interface SolarAnalysis {
  /**
   * The row this run was recorded as, or absent where it was not recorded.
   *
   * The Go side withdraws its claim to have saved by returning nothing, so the
   * absence of this is the withdrawal. Anything telling the reader the run was
   * saved has to read it.
   */
  run_id?: string
  lon: number
  lat: number
  resource: {
    ghi_annual_kwh_m2: number
    ghi_std: number
    ghi_cv_pct: number
    ghi_p10: number
    ghi_p90: number
    n_years: number
    trend_per_year: number
    trend_p_value: number
    clear_sky_index: number | null
    monthly: SolarMonth[]
  }
  geometry: {
    optimal_tilt_deg: number
    optimal_poa_kwh_m2_year: number
    surface_azimuth_deg: number
    gain_over_horizontal_pct: number
    tilt_tolerance: { deviation_deg: number; loss_pct: number }[]
  }
  pv: {
    specific_yield_kwh_kwp_year: number
    /** The ratio applied to produce the yield. */
    performance_ratio: number
    /** "reference" or "user". */
    performance_ratio_source: string
    /**
     * What the chain models. Runs high because soiling, inter-row shading,
     * degradation, availability and cabling are not modelled, so it is shown
     * for comparison rather than applied.
     */
    performance_ratio_modelled: number
    capacity_factor_pct: number
    hourly_years: number
  }
  /** The grid the figures resolve on. Always shown beside them. */
  grid_note: string
  power_provenance?: PowerProvenance | null
}

/**
 * Which NASA POWER series a run read, and when it was retrieved.
 *
 * POWER reprocesses historical data, so a series read from the on-disk cache can
 * be a superseded revision. The cache has no expiry, so that a figure benchmarked
 * against a stored run stays reproducible; what makes that safe is the run saying
 * which it was.
 */
export interface PowerSeriesProvenance {
  source: "fetch" | "cache" | "fetch_uncached"
  /** Absent for a series cached before the stamp was recorded. */
  fetched_utc: string | null
  product: string
  cell_key: string
  period: string
  cache_file: string | null
  note: string
}

export interface PowerProvenance {
  daily?: PowerSeriesProvenance | null
  hourly?: PowerSeriesProvenance | null
}

export interface SolarRequest {
  label?: string
  run_label?: string
  project_id?: string
  area_id: string
  polygon_geojson: GeoJSONGeometry | null
  climatology_years: number
  hourly_years: number
  surface_azimuth: number
  performance_ratio?: number | null
  /** The catalogued AOI this run is of, so the board can link the two. */
  aoi_id?: string
}

/**
 * Colour domain an overlay was drawn on.
 *
 * Carried by the response because the client cannot infer it and must not
 * guess. Winter and summer are deliberately given one domain: their spatial
 * spread differs by about a factor of ten, and normalising each to its own
 * range draws them at identical contrast.
 */
export interface SolarRenderScale {
  palette: PaletteName
  min: number
  max: number
  /** Value with an absolute meaning, if the quantity has one (parity at 1). */
  reference: number | null
  /** How the domain was chosen. */
  basis: "own" | "shared" | "fixed"
  shared_with: string | null
  decimals: number
}

/**
 * How much of the sky dome the terrain leaves visible, and whether the diffuse
 * loss was applied. Reported even when not applied: "not applied" and
 * "applied at zero" are different statements about the terrain.
 */
export interface SolarSkyView {
  applied: boolean
  mean_horizon_deg: number
  max_horizon_deg: number
  threshold_deg: number
  diffuse_loss_mean_pct: number | null
  diffuse_loss_max_pct: number | null
}

export interface SolarTerrainAnalysis {
  poa_min: number
  poa_max: number
  poa_mean: number
  poa_std_pct: number
  slope_mean_deg: number
  slope_max_deg: number
  pixels: number
  hourly_years: number
  dem_source: string
  season: string
  unit: string
  /**
   * Read this, not poa_min/poa_max, to build a legend: for a seasonal layer the
   * domain spans both seasons and is wider than this layer's own range.
   */
  scale: SolarRenderScale
  /** Share of beam irradiation the terrain horizon blocks, over the AOI. */
  shading_mean_pct: number | null
  shading_max_pct: number | null
  horizon_max_dist_m: number
  beam_fraction: number
  sky_view?: SolarSkyView | null
  overlay_uri: string
  raster_tif: string
  extent: Bounds
  power_provenance?: PowerProvenance | null
}

export interface SolarTerrainRequest {
  label?: string
  run_label?: string
  project_id?: string
  area_id: string
  polygon_geojson: GeoJSONGeometry | null
  hourly_years: number
  /**
   * annual, winter, summer, winter_crop, anisotropy (winter/summer), or
   * shading (share of beam blocked by the terrain horizon).
   */
  season: SolarSeason
  /** The catalogued AOI this run is of, so the board can link the two. */
  aoi_id?: string
}

export type SolarSeason =
  | "annual"
  | "winter"
  | "summer"
  | "winter_crop"
  | "anisotropy"
  | "shading"

export interface SolarSitingClass {
  code: number
  name: string
  color: string
  pixels: number
  area_ha: number
  pct: number
}

export interface SolarSitingAnalysis {
  classes: SolarSitingClass[]
  /** Never summed with the cropland class: the trade-off must stay visible. */
  suitable_no_conflict_ha: number
  suitable_cropland_ha: number
  pixel_area_ha: number
  thresholds: {
    slope_acceptable_deg: number
    slope_restrictive_deg: number
    excluded_cover: number[]
    cropland_cover: number[]
    note: string
  }
  dem_source: string
  overlay_uri: string
  raster_tif: string
  extent: Bounds
}

export interface SolarSitingRequest {
  label?: string
  run_label?: string
  project_id?: string
  area_id: string
  polygon_geojson: GeoJSONGeometry | null
  slope_acceptable_deg: number
  slope_restrictive_deg: number
  /**
   * Land-cover codes treated as excluded and as cropland. Omitted applies the
   * sidecar's defaults, and the response repeats whichever codes were used in
   * SolarSitingAnalysis.thresholds.
   */
  excluded_cover?: number[]
  cropland_cover?: number[]
  /** The catalogued AOI this run is of, so the board can link the two. */
  aoi_id?: string
}

/**
 * Request for the photovoltaic energy model.
 *
 * "energy_model" is the sidecar action identifier, kept verbatim across the
 * request, the payload key, the stored run and the export manifest so all four
 * name one thing. It is not a claim about the method.
 *
 * Every optional field left unset resolves to the sidecar default, which the
 * response echoes back under `assumptions`. A field sent as 0 where 0 is not a
 * usable value is read by the sidecar as unset, so the panel sends the default
 * rather than a blank.
 */
export interface EnergyModelRequest {
  label?: string
  run_label?: string
  project_id?: string
  area_id: string
  polygon_geojson: GeoJSONGeometry | null
  climatology_years: number
  hourly_years: number
  surface_azimuth: number
  /** Null applies the reference ratio; a value overrides it. */
  performance_ratio?: number | null
  /** "year_one" or "lifetime_mean". Empty selects year_one. */
  reporting_basis?: string
  degradation_rate_per_year?: number | null
  analysis_period_years?: number
  gcr_fixed?: number | null
  gcr_tracker?: number | null
  tracker_max_angle_deg?: number | null
  /** Key into the sidecar capacity-density table. */
  capacity_density_basis?: string
  buildable_fraction?: number | null
  /** Local offset used to label the diurnal profile. Absent means UTC. */
  utc_offset_hours?: number | null
  /** Per-term overrides of the PVWatts v5 loss stack, in percent. */
  declared_loss_pct?: Record<string, number>
  optional_loss_pct?: Record<string, number>
  slope_acceptable_deg?: number
  slope_restrictive_deg?: number
  excluded_cover?: number[]
  cropland_cover?: number[]
  /** GeoTIFF from a siting run, reused instead of reclassifying the AOI. */
  siting_raster_tif?: string
  shading_derate?: number | null
  shading_applied?: boolean
  /** The catalogued AOI this run is of, so the board can link the two. */
  aoi_id?: string
}

export interface EnergyGeometry {
  optimal_tilt_deg: number
  surface_azimuth_deg: number
  poa_kwh_m2_year: number
  poa_horizontal_kwh_m2_year: number
  ghi_hourly_kwh_m2_year: number
}

/** One declared PVWatts v5 loss the chain does not model, with its source. */
export interface EnergyLossTerm {
  key: string
  label: string
  loss_pct: number
  factor: number
  kind: string
  source: string
  user_editable: boolean
}

/**
 * A loss defaulted to zero. The value the reference suggests is reported beside
 * it rather than applied, so enabling it is a recorded decision.
 */
export interface EnergyOptionalLossTerm {
  key: string
  label: string
  loss_pct: number
  factor: number
  kind: string
  default_pct: number
  pvwatts_suggested_pct: number
  source: string
  user_editable: boolean
}

export interface EnergyPRFactors {
  energy_poa_kwh_m2_year: number
  energy_effective_kwh_m2_year: number
  energy_dc_kwh_kwp_year: number
  energy_ac_kwh_kwp_year: number
  f_iam: number
  f_temp: number
  f_inverter: number
  performance_ratio_modelled: number
  /** Residual of the identity f_iam * f_temp * f_inverter = modelled ratio. */
  telescoping_residual: number
  temp_cell_irradiance_weighted_c: number
}

export interface EnergyPerformanceRatio {
  applied: number
  applied_source: string
  reference: number
  modelled: number
  derived: number
  derived_if_optional_at_pvwatts_defaults: number
  declared_loss_factor: number
  optional_loss_factor: number
  factors: EnergyPRFactors
  declared_losses: EnergyLossTerm[]
  optional_losses: EnergyOptionalLossTerm[]
  reporting_basis: string
  degradation_factor: number
  degradation_rate_per_year: number
  analysis_period_years: number
  /** Band implied by the Global Solar Atlas at this site: [low, high]. */
  gsa_implied_band: number[]
}

/** Which PVWatts v5 module type the temperature coefficient came from. */
export interface EnergyModuleType {
  gamma_pdc_per_c: number
  module_type: string
  alternatives: Record<string, number>
  source: string
  user_editable: boolean
}

export interface EnergyWaterfallBase {
  ghi_hourly_kwh_m2_year: number
  hourly_window: string
  ghi_climatology_kwh_m2_year: number
  climatology_window: string
  note: string
}

/** Factor and cumulative_ratio are null on context rows, not multiplied in. */
export interface EnergyWaterfallStep {
  step: number
  label: string
  factor: number | null
  energy_after: number
  units: string
  cumulative_ratio: number | null
  kind: string
  in_performance_ratio: boolean
  source: string
  note: string
}

/**
 * An identity the waterfall must satisfy.
 *
 * residual is null on a checkpoint that is not an identity, so a row with no
 * residual is not read as one that closed exactly. external_band is the
 * benchmark the value is read against, empty when the checkpoint has none.
 */
export interface EnergyWaterfallCheckpoint {
  name: string
  value: number
  residual: number | null
  note: string
  external_band: number[]
}

export interface EnergyWaterfallPR {
  applied: number
  applied_source: string
  modelled: number
  derived: number
  reporting_basis: string
  degradation_factor: number
}

export interface EnergyDelivered {
  applied_kwh_kwp_year: number
  applied_capacity_factor_pct: number
  derived_kwh_kwp_year: number
  derived_capacity_factor_pct: number
  difference_pct: number
  reporting_basis: string
  note: string
}

export interface EnergyNumberSource {
  value: number
  source: string
}

export interface EnergyTextSource {
  value: string
  source: string
}

export interface EnergyWaterfallAssumptions {
  module_type: EnergyModuleType
  albedo: EnergyNumberSource
  transposition_model: EnergyTextSource
  wind_source: EnergyTextSource
  flat_placement_bias_pct: EnergyNumberSource
}

export interface EnergyLossWaterfall {
  base: EnergyWaterfallBase
  steps: EnergyWaterfallStep[]
  checkpoints: EnergyWaterfallCheckpoint[]
  outside_performance_ratio: string[]
  performance_ratio: EnergyWaterfallPR
  delivered: EnergyDelivered
  assumptions: EnergyWaterfallAssumptions
}

export interface EnergyTrackerConfiguration {
  axis_tilt_deg: number
  axis_azimuth_deg: number
  axis_azimuth_convention: string
  max_angle_deg: number
  backtrack: boolean
  terrain: string
}

export interface EnergyFixedYield {
  tilt_deg: number
  azimuth_deg: number
  poa_kwh_m2_year: number
  specific_yield_kwh_kwp_year: number
  capacity_factor_pct: number
  performance_ratio_modelled: number
}

export interface EnergyTrackerYield {
  gcr: number
  poa_kwh_m2_year: number
  specific_yield_kwh_kwp_year: number
  capacity_factor_pct: number
  performance_ratio_modelled: number
}

export interface EnergyPerKWp {
  fixed: EnergyFixedYield
  tracking: EnergyTrackerYield
  gain_pct: number
  /** Whether the comparison changes sign on this basis. */
  inverts: boolean
  note: string
}

export interface EnergySeasonRow {
  season: string
  months: number[]
  fixed_poa_kwh_m2_season: number
  tracker_poa_kwh_m2_season: number
  gain_pct: number
}

export interface EnergySeasonal {
  rows: EnergySeasonRow[]
  note: string
}

/** Measured fleet energy density, reported as published rather than derived. */
export interface EnergyBolingerDensity {
  fixed_gwh_ha_year: number
  tracking_gwh_ha_year: number
  fixed_mwh_acre_year: number
  tracking_mwh_acre_year: number
  change_pct: number
  source: string
  note: string
}

export interface EnergyOngRow {
  site: string
  dni_kwh_m2_year: number
  land_use_change_pct: number
}

export interface EnergyOngTable5 {
  site_dni_kwh_m2_year: number
  nearest_rows: EnergyOngRow[]
  band_pct: number[]
  source: string
  note: string
}

/** Both published per-hectare measurements. They disagree on the sign. */
export interface EnergyPublishedLandUse {
  bolinger_2022: EnergyBolingerDensity
  ong_2013_table5: EnergyOngTable5
  disagreement: string
}

export interface EnergyParityGCR {
  gcr_tracker: number
  gcr_ratio: number
  search_range: number[]
  note: string
}

export interface EnergyModelDerivedLandUse {
  energy_per_hectare_ratio: number
  change_pct: number
  gcr_fixed: number
  gcr_tracker: number
  gcr_ratio: number
  basis: string
  note: string
  parity: EnergyParityGCR
}

export interface EnergyPerHectare {
  published_measurements: EnergyPublishedLandUse
  model_derived: EnergyModelDerivedLandUse
  inverts: boolean
  note: string
}

export interface EnergyPRTransfer {
  wind: string
  performance_ratio_fixed: number
  performance_ratio_tracker: number
  difference_pct: number
}

export interface EnergyTrackingPR {
  applied: number
  applied_source: string
  reporting_basis: string
  transfer_between_configurations: EnergyPRTransfer[]
  transfer_range_pct: number[]
  note: string
}

export interface EnergyTracking {
  configuration: EnergyTrackerConfiguration
  per_kwp: EnergyPerKWp
  seasonal: EnergySeasonal
  per_hectare: EnergyPerHectare
  performance_ratio: EnergyTrackingPR
  excluded: string
}

/** utc_offset_hours is null when none was supplied; the hours are then UTC. */
export interface EnergyTimeStandard {
  source_standard: string
  hour_label: string
  utc_offset_hours: number | null
  note: string
}

export interface EnergyProfileMonthRow {
  month: number
  mean_ac_w_kwp: number[]
}

export interface EnergyProfileMatrix {
  units: string
  rows: EnergyProfileMonthRow[]
}

export interface EnergyMonthlyProfileRow {
  month: number
  peak_sun_hours_day: number
  poa_kwh_m2_month: number
  ac_kwh_kwp_month: number
}

export interface EnergyMonthlyProfile {
  units: Record<string, string>
  rows: EnergyMonthlyProfileRow[]
  note: string
}

export interface EnergyHourlyShareRow {
  hour: number
  share_pct: number
}

export interface EnergyHourlyShare {
  units: string
  rows: EnergyHourlyShareRow[]
}

export interface EnergyGenerationProfile {
  time_standard: EnergyTimeStandard
  mean_ac_power_by_month_and_hour: EnergyProfileMatrix
  monthly: EnergyMonthlyProfile
  share_of_annual_generation_by_hour: EnergyHourlyShare
  note: string
}

/**
 * Installed capacity per hectare with the area basis it is measured on. The
 * basis moves the answer further than the exceedance band does, so the two are
 * never reported apart.
 */
export interface EnergyCapacityDensity {
  basis: string
  value_mw_per_ha: number
  units: string
  value_mw_dc_per_ha: number
  area_basis: string
  mounting: string
  source: string
  acre_conversion: string
  buildable_fraction: number
  fleet_dc_ac_ratio: number
  ac_to_dc_conversion_applied: boolean
  note: string
}

export interface EnergyContiguity {
  largest_ha: number
  n_patches: number
  connectivity: number
  note: string
}

/** P90 is the value exceeded in 90 percent of years, so it is below P50. */
export interface EnergyExceedanceEnergy {
  p50_exceedance_gwh_year: number
  p75_exceedance_gwh_year: number
  p90_exceedance_gwh_year: number
}

export interface EnergyPlantClass {
  label: string
  area_ha: number
  capacity_dc_mw: number
  capacity_ac_mw: number
  specific_yield_kwh_kwp_year: number
  energy: EnergyExceedanceEnergy
  reporting_basis: string
  performance_ratio: number
  performance_ratio_source: string
  note: string
  contiguity: EnergyContiguity
}

/** Area only: capacity_dc_mw is null because this class needs other racking. */
export interface EnergyRestrictiveClass {
  label: string
  area_ha: number
  capacity_dc_mw: number | null
  note: string
}

export interface EnergyShading {
  derate: number
  applied: boolean
  note: string
}

export interface EnergyExceedanceLevel {
  level: number
  ghi_empirical_kwh_m2_year: number
  factor_empirical: number
  ghi_normal_kwh_m2_year: number
  factor_normal: number
  normal_fit_standard_error_kwh_m2: number
}

export interface EnergyNormality {
  test: string
  statistic: number
  p_value: number
}

export interface EnergyExceedanceCrosswalk {
  exceedance_p90_kwh_m2_year: number
  statistical_p10_kwh_m2_year: number
  exceedance_p10_kwh_m2_year: number
  statistical_p90_kwh_m2_year: number
  note: string
}

export interface EnergyExceedance {
  method_applied: string
  convention: string
  convention_note: string
  n_years: number
  mean_kwh_m2_year: number
  std_kwh_m2_year: number
  cv_pct: number
  levels: EnergyExceedanceLevel[]
  normality: EnergyNormality
  crosswalk: EnergyExceedanceCrosswalk
  linearity_assumption: string
}

export interface EnergyUncertainty {
  included: string[]
  excluded: string[]
  statement: string
  dominant_term: string
}

export interface EnergyDensityCrossCheck {
  site_mwh_ha_year: number
  reference_mwh_ha_year: number
  ratio: number
  area_basis: string
  source: string
  note: string
}

/**
 * The resource and land ceiling over the suitable area. Not an
 * interconnectable or permitted capacity, and the classes are never summed.
 */
export interface EnergyPlant {
  suitable: EnergyPlantClass
  cropland_conflict: EnergyPlantClass
  restrictive: EnergyRestrictiveClass
  areas_note: string
  capacity_density: EnergyCapacityDensity
  shading: EnergyShading
  exceedance: EnergyExceedance
  uncertainty: EnergyUncertainty
  energy_density_cross_check: EnergyDensityCrossCheck
  reporting_basis: string
  limitations: string
  /** Only `note` is filled when the caller supplied a classification. */
  thresholds: {
    slope_acceptable_deg: number
    slope_restrictive_deg: number
    excluded_cover: number[]
    cropland_cover: number[]
    note: string
  }
}

export interface EnergyAssumptions {
  performance_ratio_applied: number
  performance_ratio_source: string
  performance_ratio_modelled: number
  performance_ratio_derived: number
  reporting_basis: string
  degradation_factor: number
  degradation_rate_per_year: number
  analysis_period_years: number
  module_type: string
  transposition_model: string
  albedo: number
  gcr_fixed: number
  gcr_tracker: number
  capacity_density_basis: string
  capacity_density_mw_dc_per_ha: number
  shading_applied: boolean
  shading_derate: number
  note: string
}

/**
 * The photovoltaic energy model at the AOI.
 *
 * Shares the radiation chain with SolarAnalysis and reports the same optimum,
 * so the two products cannot disagree about one AOI. Every array field is
 * non-nullable: the Go Runner normalises each nil slice to an empty one on the
 * live path and again on restore, which is what makes that safe here.
 */
export interface EnergyModelAnalysis {
  lon: number
  lat: number
  hourly_years: number
  climatology_years: number
  hourly_window: string
  climatology_window: string
  geometry: EnergyGeometry
  performance_ratio: EnergyPerformanceRatio
  module_type: EnergyModuleType
  loss_waterfall: EnergyLossWaterfall
  tracking: EnergyTracking
  generation_profile: EnergyGenerationProfile
  capacity_density: EnergyCapacityDensity
  plant: EnergyPlant
  reporting_basis: string
  /** The grid the figures resolve on. Always shown beside them. */
  grid_note: string
  assumptions: EnergyAssumptions
  power_provenance?: PowerProvenance | null
}

/**
 * Request for the wind resource screening.
 *
 * The reanalysis cell is 0.5 by 0.625 degrees, so the response reports the
 * centre of the cell the AOI centroid falls in, not the centroid.
 */
export interface WindRequest {
  label?: string
  run_label?: string
  project_id?: string
  area_id: string
  polygon_geojson: GeoJSONGeometry | null
  record_years: number
  hub_height_m?: number | null
  calm_threshold_ms?: number | null
  record_max_floor_ms?: number | null
  /** Two roughness lengths in metres: the assumed land-cover band. */
  roughness_band_m?: number[]
  /** The catalogued AOI this run is of, so the board can link the two. */
  aoi_id?: string
}

export interface WindWeibullFitCheck {
  empirical_mean_ms: number
  weibull_mean_ms: number
  mean_error_pct: number
  empirical_mean_cube_m3s3: number
  weibull_mean_cube_m3s3: number
  mean_cube_error_pct: number
  estimator: string
}

export interface WindMonthlySpeed {
  month: number
  mean_speed_ms: number
}

/** The convention is the direction the wind comes from, stated because the
 * opposite convention is also in use. */
export interface WindDirection {
  convention_note: string
  circular_mean_deg_10m: number
  circular_mean_deg_50m: number
  median_turning_deg: number
}

/** energy_pct and hours_pct differ because energy goes as the cube of speed. */
export interface WindRoseSector {
  sector: number
  centre_deg: number
  energy_pct: number
  hours_pct: number
}

/** What the reanalysis carries directly at 10 m and 50 m: no extrapolation. */
export interface WindMeasured {
  qualifier: string
  mean_speed_10m_ms: number
  mean_speed_50m_ms: number
  shear_exponent: number
  weibull_k_50m: number
  weibull_c_50m_ms: number
  weibull_fit_check_50m: WindWeibullFitCheck
  energy_pattern_factor_50m: number
  wind_power_density_50m_w_m2: number
  air_density_mean_kg_m3: number
  air_density_min_kg_m3: number
  air_density_max_kg_m3: number
  monthly_mean_speed_50m: WindMonthlySpeed[]
  direction: WindDirection
  direction_energy_rose_50m: WindRoseSector[]
}

export interface WindExtrapolation {
  hub_height_m: number
  interpolation_ceiling_m: number
  height_ratio: number
  is_extrapolation: boolean
  statement: string
}

export interface WindOperatingRegime {
  above_cut_in_pct: number
  at_or_above_rated_pct: number
  above_cut_out_pct: number
  cut_in_ms: number
  rated_ms: number
  cut_out_ms: number
}

/**
 * The hub-height result. Gross: no wake, availability, electrical, icing or
 * curtailment loss is applied, and there is no external validation.
 */
export interface WindHub {
  qualifier: string
  extrapolation: WindExtrapolation
  mean_speed_ms: number
  weibull_k: number
  weibull_c_ms: number
  wind_power_density_w_m2: number
  gross_capacity_factor_pct: number
  gross_capacity_factor_no_density_correction_pct: number
  gross_annual_energy_mwh_per_turbine: number
  operating_regime: WindOperatingRegime
  hours_per_year: number
  excluded_losses: string[]
}

/** roughness_length_m is null on the row derived from the record itself, which
 * inverts to a roughness rather than assuming one. */
export interface WindShearRow {
  shear_exponent: number
  roughness_length_m: number | null
  basis: string
  hub_speed_ms: number
  capacity_factor_pct: number
  annual_energy_mwh: number
}

export interface WindShearDiagnostics {
  shear_exponent: number
  /**
   * Null when the shear exponent lies outside the range a neutral logarithmic
   * profile between 10 m and 50 m can produce for any roughness length:
   * terra/energy/wind.py implied_roughness_length returns NaN there and the
   * serialiser writes null. Declared nullable because Go decodes that null into
   * a float64 zero, and rendered as a number it printed "0.000 m" for a value
   * that was never computed, beside prose saying the inversion has no root.
   */
  implied_roughness_length_m: number | null
  assumed_roughness_band_m: number[]
  expected_shear_exponent_band: number[]
  consistent_with_assumed_cover: boolean
  shear_exponent_hourly_mean: number
  shear_exponent_hourly_median: number
  shear_exponent_day: number
  shear_exponent_night: number
  local_utc_offset_hours: number
}

/**
 * The record's own account of itself. all_checks_passed false with a populated
 * flags list is the signal that the hub figures rest on a series the checks do
 * not support.
 */
export interface WindDataQuality {
  record_hours: number
  expected_hours: number
  mean_speed_ms: Record<string, number>
  calm_fraction_pct: Record<string, number>
  calm_threshold_ms: number
  record_maximum_ms: Record<string, number>
  record_maximum_floor_ms: number
  record_maximum_plausible: boolean
  calm_fraction_2m_flag_pct: number
  nan_count: Record<string, number>
  shear: WindShearDiagnostics
  flags: string[]
  all_checks_passed: boolean
}

/** A reference power curve, not a turbine selected for this site. */
export interface WindTurbine {
  name: string
  rated_power_w: number
  rotor_diameter_m: number
  hub_height_m: number
  blades: number
  iec_class: string
  turbulence_class: string
  cut_in_ms: number
  rated_speed_ms: number
  cut_out_ms: number
  power_curve_points: number
  power_curve_column: string
  citation: string
  citation_url: string
  curve_source_url: string
  curve_source_commit: string
}

export interface WindAssumptions {
  hub_height_m: number
  hub_height_source: string
  record_years: number
  record_window: string
  shear_exponent: number
  shear_exponent_source: string
  roughness_band_m: number[]
  calm_threshold_ms: number
  record_max_floor_ms: number
  qualifier: string
  excluded_losses: string[]
  /** States that the wind capacity factor is not comparable with the PV one. */
  comparison_note: string
}

/**
 * A wind resource screening at the AOI, from reanalysis hourly wind.
 *
 * A screening indication and not a resource assessment: the hub figures are
 * gross of every plant loss, carry no external validation, and rest on a
 * power-law extrapolation above the highest level the data carries. Its
 * capacity factor must never be placed beside the photovoltaic one, which is
 * benchmarked against the Global Solar Atlas.
 *
 * Array fields are non-nullable for the reason given on
 * EnergyModelAnalysis.
 */
export interface WindAnalysis {
  lon: number
  lat: number
  /** Centre of the reanalysis cell the AOI resolves to, [lon, lat]. */
  grid_cell_centre: number[]
  grid_note: string
  record_years: number
  record_window: string
  hub_height_m: number
  qualifier: string
  measured: WindMeasured
  hub: WindHub
  shear_sensitivity: WindShearRow[]
  data_quality: WindDataQuality
  turbine: WindTurbine
  assumptions: WindAssumptions
  power_provenance?: PowerProvenance | null
}

/**
 * Request for the flood envelope.
 *
 * The optional fields are absent rather than zero when they are not being
 * set: the sidecar reads a missing key as "choose the default", and 0 is a
 * legitimate request for three of them -- a reference threshold of 0 m asks
 * for the drainage surface itself, a buffer of 0 m for exactly the AOI, an
 * inset margin of 0 cells for no inset ring. Sending a default as an
 * explicit 0 asks for a different analysis than the one intended.
 */
export interface FloodRequest {
  area_id: string
  polygon_geojson: GeoJSONGeometry | null
  /**
   * The products to compare, by DEM collection id. Absent selects the
   * four-product default set. Fewer than two the sidecar refuses: one product
   * yields an extent with no measure of how much of it that product chose,
   * which is the shape this analysis exists not to ship.
   */
  dem_ids?: string[]
  /** HAND thresholds in metres to sweep. Absent selects the study's sweep. */
  thresholds_m?: number[]
  /** Where the agreement raster is built. Need not appear in thresholds_m. */
  reference_threshold_m?: number
  /** Contributing area above which a cell counts as drainage. Zero is refused. */
  drainage_km2?: number
  /** How far beyond the AOI to read each DEM, so inflowing drainage is real terrain. */
  buffer_m?: number
  /**
   * Ring cut from inside the AOI polygon for the inset statistics.
   *
   * The key is inset_margin_cells and not the edge_margin_cells this once
   * sent: the ring used to come off the computed window, it now comes off the
   * AOI, and the sidecar refuses the old key by name rather than accept a
   * number that would describe a different ring than the one reported back.
   */
  inset_margin_cells?: number
  label?: string
  run_label?: string
  project_id?: string
  /** The catalogued AOI this run is of, so the board can link the two. */
  aoi_id?: string
}

/**
 * Ground size of one grid cell in metres, at the centre latitude of the
 * window. Every area in this analysis is a cell count times this, so it is not
 * a projected-area calculation and the two differ across the window.
 */
export interface FloodCellSize {
  x: number
  y: number
}

/**
 * The window the terrain chain ran on, which is provenance and NOT the extent
 * anything is reported over.
 *
 * This is the AOI plus FloodAnalysis.buffer_m on each side, less the border
 * cells trimmed to a rectangle every product covers. Nothing in this payload
 * is measured over it -- FloodAOI is what every count, area and index covers
 * -- and `bounds` places FloodAnalysis.agreement_tif alone, never the PNG. In
 * the recorded payload it is 43848 cells against the AOI's 5256, so a figure
 * read against these cells overstates the ground it describes by 8.3 times:
 * that reading is how a 4.5 km2 AOI came to be reported as 37.5 km2 of
 * classified land.
 */
export interface FloodGrid {
  width: number
  height: number
  bounds: Bounds
}

/**
 * The ground every figure in this payload is measured over: the cells whose
 * centre falls inside the AOI polygon.
 *
 * It carries the computed window beside itself because either number alone
 * misleads. `area_km2` alone hides that the terrain was solved over more
 * ground than is reported, which is what makes the areas trustworthy;
 * `window_area_km2` alone is the figure that used to be on screen. A cell is
 * in or out by its centre, so `area_km2` and the polygon's own area differ by
 * at most a half cell along the boundary.
 */
export interface FloodAOI {
  cells: number
  area_km2: number
  /**
   * Cells left after FloodAnalysis.inset_margin_cells is cut from the polygon,
   * which is the denominator of every inset index.
   */
  inset_cells: number
  /** The buffered window the chain ran over, as cells and as ground. */
  window_cells: number
  window_area_km2: number
  /** AOI cells over window cells: how much of what was solved is reported. */
  frac_of_window: number
}

/**
 * One DEM product's extent at the reference threshold, counted inside the AOI
 * polygon. `area_frac` is of FloodAOI.cells and not of the window, so it is a
 * share of the ground the reader drew.
 */
export interface FloodProduct {
  id: string
  collection: string
  /**
   * Nullable because null here means the fact was not recorded, not that the
   * resolution is 0 m or that the product was left on its own grid. Read as a
   * plain number and boolean, a null prints as a measurement that was never
   * made -- and `resampled` is the one column separating a terrain difference
   * from a resampling artefact.
   */
  native_resolution_m: number | null
  resampled: boolean | null
  cells: number
  area_km2: number
  area_frac: number
}

/**
 * The agreement count raster summarised. Unanimous cells are where the terrain
 * decides the extent; contested cells are where the choice of DEM decides it.
 */
export interface FloodAgreement {
  /**
   * AOI cells at each agreement level, indexed by how many products call the
   * cell flooded, so it carries one entry more than there are products and
   * sums to FloodAOI.cells -- not to grid.width times grid.height.
   *
   * counts[0] closes that accounting and is not a level of agreement: that no
   * product calls a cell flooded says nothing about how far the products agree
   * with each other, and a legend listing it as a class beside the others
   * flattens the one distinction this analysis draws. It is
   * unanimous_dry_km2, the dry remainder of the AOI, and the raster leaves
   * those cells transparent.
   */
  counts: number[]
  unanimous_wet_km2: number
  contested_km2: number
  unanimous_dry_km2: number
  /**
   * contested / (contested + unanimous wet). Null when no product calls
   * anything wet: there is no extent to take a share of, and rendering the
   * null as 0 would state perfect agreement over an AOI nobody called flooded.
   */
  contested_frac_of_wet: number | null
}

/**
 * Two products compared at one threshold.
 *
 * iou is the Jaccard index between the two binary extents. For a binary mask it
 * is numerically the critical success index (CSI) of the flood literature, and
 * a reader from hydrology looks for that name rather than this one.
 */
export interface FloodPair {
  dem_a: string
  dem_b: string
  threshold_m: number
  /**
   * Null when both extents are empty: the index is undefined over an empty
   * union, and 0 would state total disagreement between two products that
   * agree the AOI is dry.
   */
  iou: number | null
  /**
   * The same over the AOI shrunk by FloodAnalysis.inset_margin_cells. The ring
   * is cut from the polygon and not from the computed window, which the buffer
   * already puts outside every figure here. What it tests is unchanged:
   * whatever drains in from beyond the buffer is missing for the cells nearest
   * the AOI boundary first, so there HAND reads high and the extent small, and
   * a large gap from iou says the disagreement sits at the edge of the
   * reported area rather than through the middle of it.
   */
  iou_inset: number | null
  /**
   * Null when dem_a has no wet cell at this threshold, rather than a ratio over
   * a denominator of one cell, which would report that fact as 1.0.
   */
  area_ratio_b_over_a: number | null
  /**
   * Whether either side was moved onto the shared grid before its terrain chain
   * ran. True rows carry a resampling component alongside the terrain
   * difference, of the size quantified in FloodAssumptions.chain_grid; only the
   * false rows compare terrain alone. Null means the fact was not recorded,
   * which is not the same as false.
   */
  resampled: boolean | null
}

/**
 * The range the products span at one threshold: the narrowest and widest
 * pairwise agreement. Null throughout when no pair yielded a defined index.
 */
export interface FloodEnvelopeRow {
  threshold_m: number
  iou_min: number | null
  iou_max: number | null
  iou_min_inset: number | null
  iou_max_inset: number | null
}

/**
 * Every default the figures rest on, where it came from, and what is left out.
 * Prose written by the sidecar and carried verbatim; each entry names a choice
 * and states what moves if it changes.
 */
export interface FloodAssumptions {
  drainage_threshold: string
  reference_threshold: string
  thresholds: string
  /**
   * Which cells the figures are taken over, in the numbers of this run: the
   * AOI against the buffered window the chain solved. It travels with any area
   * quoted from this payload, because an area is a figure a reader attributes
   * to ground and this names which ground.
   */
  reporting_extent: string
  inset_margin: string
  cell_size: string
  alignment: string
  buffer: string
  /**
   * Which raster covers what. The GeoTIFF is the whole computed window and the
   * PNG is the AOI clip, so the two are not the same picture and a reader who
   * takes the GeoTIFF into a GIS sees ground no figure here describes.
   */
  rasters: string
  /**
   * The order the chain ran in and its measured cost: every product ran HAND on
   * the shared grid, so a coarser product was resampled before the chain rather
   * than after, and the two orders agreed at IoU 0.47 for the 90 m product
   * against 0.95 for a 30 m one over one window (n=1). That is the size of the
   * disagreement this analysis exists to report, so this string has to travel
   * wherever a resampled pair's figure does.
   */
  chain_grid: string
  excluded: string[]
}

/**
 * A HAND flood extent and the disagreement between the DEM products it can be
 * derived from.
 *
 * The envelope is TERRA's own measurement over the products it reads from
 * Microsoft Planetary Computer. It is not the range published by the study this
 * ports, which measured a different product set from a different catalogue;
 * quoting that range beside these figures would attribute someone else's
 * measurement to this map. `qualifier` carries the sentence that must travel
 * with any figure taken from here, so nothing should render a number from this
 * block without a route to it.
 *
 * Array fields are non-nullable for the reason given on EnergyModelAnalysis.
 */
export interface FloodAnalysis {
  reference_threshold_m: number
  thresholds_m: number[]
  drainage_km2: number
  cell_size_m: FloodCellSize
  /** Provenance: the window the chain ran on. `aoi` is what the figures cover. */
  grid: FloodGrid
  buffer_m: number
  aoi: FloodAOI
  products: FloodProduct[]
  agreement: FloodAgreement
  pairs: FloodPair[]
  envelope: FloodEnvelopeRow[]
  inset_margin_cells: number
  qualifier: string
  assumptions: FloodAssumptions
  /**
   * The agreement counts as a single-band GeoTIFF, georeferenced on exactly
   * grid.bounds -- the whole computed window, buffer included. A path on the
   * machine that ran the analysis, not something the webview can open: it is
   * what a reader takes into a GIS, and the interface can only name it.
   */
  agreement_tif: string
  /**
   * The same counts rendered for display, clipped to the AOI bounding box with
   * every cell outside the polygon transparent, so the overlay covers what the
   * figures cover. Also a server-side path.
   */
  agreement_png: string
  /**
   * Where agreement_png goes on the map: the bounds of that clipped image
   * ALONE. grid.bounds is the buffered window, and placing the clip on it
   * stretches the overlay over several times the ground it covers -- the same
   * mistake in pixels that reporting over the window was in numbers. Same
   * field shape as WaterAnalysis.extent, so one placement path serves both.
   */
  extent: Bounds
  /**
   * agreement_png as a data URI, which is how every raster this program draws
   * reaches the webview. Empty or absent when the rendering could not be read,
   * in which case the numbers still stand and only the map is missing.
   */
  agreement_uri?: string
  /**
   * The same crop carrying the COUNTS rather than their colours, as a data
   * URI: the count in the red channel, one per byte, alpha marking the
   * reporting mask.
   *
   * It exists so the map can colour the raster from an expression rather than
   * draw a finished image -- agreement_uri's palette, and which counts it
   * draws at all, were decided in the sidecar. Absent when the file could not
   * be read, in which case the map draws agreement_uri and only the palette
   * control is missing.
   */
  agreement_values_uri?: string
  agreement_values_png?: string
}
