// Types mirroring the Go backend structs (backend/types.go). The Wails bridge
// also generates models under wailsjs/go/models.ts after `wails dev`; these
// local definitions keep the frontend readable and self-contained.
//
// Being a hand copy, this file can drift from the structs it mirrors without
// anything failing. scripts/check-types.ts compares the JSON field names of
// every struct that has a same-named interface here and exits non-zero when
// the two sets differ; it says in its own header what it does not compare.

export interface Bounds {
  lon_min: number
  lat_min: number
  lon_max: number
  lat_max: number
}

export interface GeoJSONGeometry {
  type: string
  coordinates: number[][][]
}

export type ModelKind = "spectral" | "prithvi" | "temporal_transformer"

export interface PredictRequest {
  polygon_geojson: GeoJSONGeometry | null
  start: string
  end: string
  max_cloud: number
  monthly_best: boolean
  tiles: string[]
  mode: "single" | "temporal"
  model_kind: ModelKind
  prithvi_mode: "pixel" | "patch"
  /** Attach the saved run to this project when set. */
  project_id?: string
  /** Display name for the AOI (a rename, or the area's own name). */
  label?: string
  /** Inference run title (run-…). Generated by backend if omitted. */
  run_label?: string
  /** The area this run is of, so the board can link the two. */
  area_id?: string
}

export interface ClassStat {
  class_id: number
  name: string
  color: string
  pixels: number
  pct: number
  area_ha: number
}

/** One band of a reference spectrum from a spectral library. */
export interface LibraryBand {
  band: string
  wavelength_nm: number
  reflectance: number
}

/**
 * The material a comparison is made against.
 *
 * `level` decides how the result may be read. A leaf-level reference against a
 * canopy pixel cannot identify a material however small the angle, because the
 * two are not measurements of the same thing.
 */
export interface LibraryReference {
  material: string
  source: string
  package_id: string
  n_spectra: number
  level: string
  note: string
  bands: LibraryBand[]
}

export interface LibraryClassBand {
  band: string
  wavelength_nm: number
  canopy: number
  leaf: number
  /** Canopy over leaf. Constant would be brightness, which the angle ignores. */
  ratio: number | null
  unit_canopy: number | null
  unit_leaf: number | null
}

export interface LibraryClass {
  class_id: number
  name: string
  color: string
  angle_rad: number
  bands: LibraryClassBand[]
}

/**
 * The cross-reference against a spectral library, and its limit.
 *
 * Classes are ordered by angle, closest first, and the ordering is the point:
 * the class named Soybean is not the one closest to the soybean reference. A
 * small angle here means CONSISTENCY and never identification.
 */
export interface LibraryLimit {
  reference: LibraryReference
  scene_date: string
  classes: LibraryClass[]
}

/** One band, for one predicted class, on one acquisition. */
export interface ClassSpectrumPoint {
  class_id: number
  name: string
  color: string
  band: string
  wavelength_nm: number
  n_pixels: number
  mean: number
  sd: number
  p05: number
  p95: number
}

/**
 * The measured spectral response per predicted class.
 *
 * `scene_date` is not provenance trim. The classification spans the period and
 * the reflectance is one acquisition, so a reader who takes the curve for a
 * seasonal mean is reading something this payload does not contain.
 */
export interface ClassSpectra {
  scene_date: string
  scene_id?: string
  n_scenes: number
  convention: string
  bands: string[]
  points: ClassSpectrumPoint[]
}

export interface TemporalPoint {
  date: string
  n_dates_stack: number
  soja_ndvi_mean: number | null
  soja_retention_pct: number | null
  dominant: string | null
}

export interface VISeriesPoint {
  date: string
  ndvi_mean: number
  ndvi_std: number
  evi_mean: number
  evi_std: number
  savi_mean: number
  savi_std: number
}

export interface PhenologyMetrics {
  sos_doy: number | null
  pos_doy: number | null
  eos_doy: number | null
  los_days: number | null
  peak: number | null
  base: number | null
  amplitude: number | null
}

export interface PhenologyStatePoint {
  date: string
  state: number
  state_name: string
  color: string
  ndvi_mean: number | null
}

export interface LULCClassRow {
  class_id: number
  name: string
  color: string
  group: string
  pixels: number
  pct: number
  area_ha: number
}

export interface LULCGroupRow {
  group: string
  color: string
  pct: number
  area_ha: number
}

export interface LULCMetrics {
  area_ha: number
  n_pixels: number
  n_classes: number
  shannon_h: number
  pielou_j: number
  dominant_class: string
  dominant_pct: number
  soja_pct: number
  outras_lav_pct: number
  agricola_pct: number
}

export interface LULCCompareRow {
  class_id: number
  name: string
  color: string
  pct_ref: number
  pct_pred: number
  /** 10 m pixels of this class in the reference, on the classification grid. */
  pixels_ref?: number
  /**
   * Distinct native 30 m MapBiomas cells behind those pixels. This is the
   * number of independent label observations; the pixel count is about nine
   * times larger and is not a sample size.
   */
  n_reference_cells?: number
}

/** One class's producer's and user's accuracy, each with a 95% interval. */
export interface LULCClassAccuracy {
  class_id: number
  name: string
  color: string
  /** Of the reference cells of this class, the share the classifier found. */
  producers_pct: number | null
  producers_ci?: [number, number]
  /** Of the cells called this class, the share that really are. */
  users_pct: number | null
  users_ci?: [number, number]
  n_reference: number
  n_predicted: number
}

/**
 * Agreement against the reference — what the composition comparison cannot say.
 *
 * Two maps holding identical proportions of every class can disagree on every
 * cell, so the composition rows and this measure different things. Computed
 * over the reference's native 30 m cells, not the 10 m pixels resampled from
 * them, because nine pixels carrying one label are one observation.
 */
export interface LULCAgreement {
  n_reference_cells: number
  overall_pct: number
  overall_ci: [number, number]
  /** Pontius & Millones (2011): different amounts vs. different places. */
  quantity_disagreement_pct: number
  allocation_disagreement_pct: number
  per_class: LULCClassAccuracy[]
  /** Reference cells whose class the classifier has no label for. */
  n_outside_legend: number
  /**
   * Rows are the classification, columns the reference.
   *
   * `agreement_against_reference` fills `matrix[pred][ref]` and derives
   * producer's accuracy from the column totals. Read the other way round it
   * still looks like a confusion matrix and reports commission as omission,
   * which is why the orientation is stated here and not left to the reader.
   */
  matrix: number[][]
  matrix_classes: number[]
  /** Absent where no block held enough reference cells to carry a figure. */
  blocks?: LULCAgreementBlocks | null
}

/**
 * Agreement over a fixed grid of spatial blocks.
 *
 * `overall_pct` cannot tell a classifier that is uniformly mediocre from one
 * that is accurate everywhere but a corner, and the two call for different
 * work. Descriptive rather than inferential: the blocks are a grid over the
 * raster's extent, not a sampling design.
 */
export interface LULCAgreementBlocks {
  rows: number
  cols: number
  /** Reference cells a block needs before its percentage is reported. */
  min_cells: number
  cells: LULCAgreementBlock[]
  n_measured: number
  median_pct: number
  iqr_pct: number
  min_pct: number
  max_pct: number
}

export interface LULCAgreementBlock {
  row: number
  col: number
  n_reference_cells: number
  /** Null below `min_cells`: arithmetic rather than a measurement. */
  overall_pct: number | null
}

export interface LULCAnalysis {
  year: number
  source: string
  map_uri?: string
  extent?: Bounds
  metrics: LULCMetrics
  composition: LULCClassRow[]
  groups: LULCGroupRow[]
  pred_vs_ref: LULCCompareRow[]
  /** Valid 10 m pixels shared by both maps. */
  compare_pixels?: number
  /** Distinct native reference cells behind them; the comparison sample size. */
  compare_reference_cells?: number
  /** Absent when the reference cell mapping was unavailable. */
  agreement?: LULCAgreement
}

export interface LULCRequest {
  polygon_geojson?: GeoJSONGeometry | null
  mapbiomas_path?: string
}

export interface PredictResult {
  /**
   * The saved run this result became, when one was saved.
   *
   * Set by the backend after persisting, so it is absent from the stored copy
   * of a run's own result. Compositions made while this result is on screen
   * attach to it.
   */
  run_id?: string
  extent: Bounds
  overlay_uri: string
  confidence_uri: string
  ndvi_mean_uri: string
  true_color_uri: string
  reference_uri: string
  raster_tif: string
  /**
   * Mean of max(predict_proba) over classified pixels.
   *
   * Ensemble vote share, not a calibrated probability of being correct:
   * Random Forest vote fractions are biased toward the middle of the range
   * (Niculescu-Mizil & Caruana 2005). Read it with confidence_floor.
   */
  mean_confidence: number
  /** 1/K for a K-class model; the value mean_confidence cannot go below. */
  confidence_floor?: number
  n_dates: number
  // Go marshals a nil slice as null, and a run that produced no classification
  // -- a water or flood run, which needs no classification -- leaves every one
  // of these nil. Declared nullable so each read has to be guarded; taken as guaranteed,
  // one of them blanked the whole application.
  date_range: string[] | null
  /**
   * The side of one predicted pixel on the ground, in metres, off the grid the
   * run was made on. Absent on runs saved before it was carried.
   */
  pixel_size_m?: number
  class_stats: ClassStat[] | null
  /**
   * Absent on older runs, on the non-spectral model paths, and when the scene
   * behind the classification could not be re-read for its bands.
   */
  class_spectra?: ClassSpectra | null
  /** The same spectra measured against a spectral library. */
  library_limit?: LibraryLimit | null
  temporal: TemporalPoint[] | null
  vi_series: VISeriesPoint[] | null
  /**
   * The same dates averaged over CROP PIXELS ONLY, beside the AOI-wide series
   * rather than in place of it.
   *
   * The two can differ in length -- a date whose crop pixels were entirely
   * cloud-obscured leaves this series and stays in the other -- so they must be
   * read by date and never zipped by index. Absent when the AOI carries no
   * cropland, which is a statement and not a failure. Anything inverting an
   * index to leaf area should prefer this one: an area mean over mixed cover is
   * not the crop's index.
   */
  vi_series_crop?: VISeriesPoint[]
  /** The crop share of the AOI, in percent; the denominator for the series above. */
  crop_pixel_pct?: number
  phenology: PhenologyMetrics
  phenology_states: PhenologyStatePoint[] | null
  lulc?: LULCAnalysis | null
  /** Attached when a surface-water run was made over the same AOI. */
  water?: WaterAnalysis | null
  /**
   * A HAND flood envelope: the extent together with the disagreement between
   * the DEM products it can be derived from. Never one product's mask alone --
   * the study this ports found the mask is not reproducible across products,
   * so a lone extent is a shape some DEM chose and the reader is never shown
   * the choice.
   */
  flood?: FloodAnalysis | null
  /**
   * Compact spectral / NDVI fingerprint cached at classify time for
   * domain-shift diagnostics. Absent on older runs and non-classify products.
   */
  domain_fingerprint?: DomainFingerprint | null
}

/** Fixed-edge histogram (NDVI by default). */
export interface DomainHistogram {
  edges: number[]
  counts: number[]
  probs: number[]
}

export interface DomainRedNIR {
  red_mean: number
  nir_mean: number
}

/** Per-run domain summary used by AnalyzeDomainShift. */
export interface DomainFingerprint {
  space: string
  n_features: number
  n_pixels: number
  n_sample: number
  mean: number[]
  var: number[]
  /**
   * In training standard deviations, from the model's own scaler.
   *
   * These decide whether a comparison can be standardised at all. Their
   * absence is what makes the sidecar refuse, and an unstandardised distance
   * is dominated by acquisition-index features rather than by reflectance.
   */
  z_mean?: number[] | null
  z_var?: number[] | null
  feature_names?: string[] | null
  feature_importances?: number[] | null
  ndvi_hist?: DomainHistogram | null
  red_nir?: DomainRedNIR | null
  sample?: number[][] | null
}

/**
 * The kernel two-sample statistic, with what it needs to be read.
 *
 * Not a scalar: MMD is not comparable across bandwidths, so the gamma the
 * median heuristic chose travels with it, as do the sample sizes.
 */
export interface DomainShiftMMD {
  mmd2?: number | null
  gamma?: number | null
  n_a: number
  n_b: number
}

/** One row of the per-feature displacement table. */
export interface DomainFeatureShift {
  feature: string
  z_a: number
  z_b: number
  /** Displacement in training standard deviations. */
  gap_sd: number
  /** Impurity importance from the fitted forest; null for other spaces. */
  importance?: number | null
  /** gap_sd weighted by importance: movement the model actually reads. */
  weighted: number
}

export interface DomainShiftPoint {
  x: number
  y: number
  domain: string
}

export interface DomainShiftProjection {
  method: string
  points: DomainShiftPoint[]
  /**
   * "standardised" or "raw".
   *
   * The axes carry no units either way, but the two are different pictures: on
   * raw features the geometry is set by the acquisition indices, which span
   * 0..21 against reflectances near 0.1.
   */
  space?: string
}

/** One class's precision, recall and F1, from the agreement matrix. */
export interface DomainShiftClassF1 {
  index: number
  /** Null only when the matrix arrived without its axis order. */
  class_id?: number | null
  precision?: number | null
  recall?: number | null
  f1?: number | null
}

export interface DomainShiftAgreementBlock {
  label: string
  overall_pct?: number | null
  n_outside_legend: number
  outside_legend_pct?: number | null
  quantity_disagreement_pct?: number | null
  allocation_disagreement_pct?: number | null
  macro_f1?: number | null
  /**
   * Per-class precision, recall and F1.
   *
   * A macro average says the model got worse; only these say which class. The
   * sidecar has emitted them all along and the Go struct declared no field, so
   * they were dropped at the unmarshal boundary.
   */
  per_class_f1?: DomainShiftClassF1[] | null
}

/**
 * One target measured against the source.
 *
 * Mirrors `DomainShiftReport` minus the histograms, the projection and the
 * feature-shift table: those are per-pair readings and a cohort consumes none
 * of them. A reader who wants them opens the pair.
 */
export interface DomainShiftCohortRow {
  id: string
  label: string
  space_a?: string
  space_b?: string
  kl_ndvi?: number | null
  kl_ndvi_a_to_b?: number | null
  kl_ndvi_b_to_a?: number | null
  same_space: boolean
  standardised: boolean
  cva_magnitude?: number | null
  cva_magnitude_sd?: number | null
  cva_angle_red_nir_deg?: number | null
  mmd_rbf?: DomainShiftMMD | null
  /**
   * Whether this row may sit on the same axis as the others.
   *
   * The two qualifiers resolved to the question the view asks. A row that
   * cannot is not a low score — it is a distance in other units, and plotting
   * it beside the rest is the unqualified comparison the qualifiers exist to
   * prevent.
   */
  comparable: boolean
  agreement_a?: DomainShiftAgreementBlock | null
  agreement_b?: DomainShiftAgreementBlock | null
}

export interface DomainShiftCohortSource {
  id: string
  label: string
  space?: string
  agreement?: DomainShiftAgreementBlock | null
}

/** One source against N targets: the star the transferability question has. */
export interface DomainShiftCohort {
  source: DomainShiftCohortSource
  targets: DomainShiftCohortRow[]
}

/** Diagnosis payload from two fingerprints (KL / CVA / MMD / F1). */
export interface DomainShiftReport {
  space_a?: string
  space_b?: string
  kl_ndvi?: number | null
  kl_ndvi_a_to_b?: number | null
  kl_ndvi_b_to_a?: number | null
  /**
   * Whether the two fingerprints describe the same feature space, and whether
   * both carried the moments needed to standardise. Every distance in this
   * report is unqualified without them.
   */
  same_space?: boolean
  standardised?: boolean
  cva_magnitude?: number | null
  /** The figure to read: the raw magnitude is dominated by index features. */
  cva_magnitude_sd?: number | null
  cva_angle_red_nir_deg?: number | null
  mmd_rbf?: DomainShiftMMD | null
  /** Where the shift is, by feature, in training standard deviations. */
  feature_shift?: DomainFeatureShift[] | null
  ndvi_hist_a?: DomainHistogram | null
  ndvi_hist_b?: DomainHistogram | null
  agreement_a?: DomainShiftAgreementBlock | null
  agreement_b?: DomainShiftAgreementBlock | null
  projection?: DomainShiftProjection | null
}

export interface ProgressEvent {
  progress: number
  msg: string
}

export interface GeocodeResult {
  display_name: string
  lat: number
  lon: number
  bounding_box: number[]
}

export interface User {
  id: string
  email: string
  display_name: string
  avatar_path?: string
  avatar_uri?: string
  created_at: string
  updated_at: string
}

export interface Preferences {
  user_id: string
  default_model: string
  overlay_opacity: number
  theme: string
  extras_json?: string
}



export interface InferenceRun {
  id: string
  user_id: string
  created_at: string
  model_kind: string
  period_start: string
  period_end: string
  polygon_geojson: string
  status: string
  summary: string
  result_json?: string
  overlay_relpath?: string
  assets_relpath?: string
  n_dates: number
  label?: string
  project_id?: string
  /** "classification" or "water"; empty on rows written before the column. */
  kind?: string
  /**
   * The ground this run was made over: a row in the project's areas.
   *
   * The polygon says WHERE the run was made; this says which area it is OF.
   * The board reads it to keep an area and the runs over it as one subject
   * instead of one outline per area plus one per run. Absent for a run put
   * back from a shape that was never made an area, which resolves by geometry.
   */
  area_id?: string
}

export interface Project {
  id: string
  user_id: string
  name: string
  notes?: string
  created_at: string
  updated_at: string
  /**
   * The ground the reader was last on in this project.
   *
   * A cursor, not a property: it says where to resume. It replaces
   * `polygon_geojson`, `area_id` and `label`, which gave the project a
   * geometry of its own — one shape for a workspace holding as many grounds as
   * a reader draws, written from whatever happened to be on the map.
   *
   * An id that no longer resolves means no cursor. Deleting an area clears it
   * on every project pointing at it.
   */
  last_area_id?: string
  /** Grounds this project holds. Counted by the listing query. */
  area_count?: number
  run_count?: number
  overlay_count?: number
}

export interface ProjectOverlay {
  id: string
  project_id: string
  /**
   * The run on screen when this composition was made.
   *
   * Empty for one made with no run open, and for every row written before the
   * column existed. Empty means "belongs to the project", so those are scoped
   * by their recorded extent instead.
   */
  run_id?: string
  /** The area it was made over; empty on rows written before it was carried. */
  area_id?: string
  kind: string
  title: string
  meta_json?: string
  png_relpath?: string
  tif_relpath?: string
  created_at: string
  overlay_uri?: string
  raster_tif?: string
}

export interface SaveProjectOverlayRequest {
  /** The run on screen when the composition was made, when there was one. */
  run_id?: string
  /** The area it was made over, which files a composition that has no run. */
  area_id?: string
  project_id: string
  kind: string
  title: string
  meta_json: string
  overlay_uri: string
  raster_tif?: string
}

export interface DataCubeRequest {
  polygon_geojson: GeoJSONGeometry | null
  start: string
  end: string
  max_cloud: number
  monthly_best: boolean
  tiles: string[]
}

export interface DataCubeScene {
  id: string
  date: string
  cloud_cover: number
  tile: string
  satellite: string
  preview_uri?: string
}

export interface DataCubeResult {
  n_scenes: number
  scenes: DataCubeScene[]
  date_range: string[]
  monthly_best: boolean
  max_cloud: number
}

export type CompositeKind = "rgb" | "index"
export type CompositeIndex = "ndvi" | "ndwi" | "ndmi" | "evi"

export interface CompositeRequest {
  polygon_geojson: GeoJSONGeometry | null
  start: string
  end: string
  max_cloud: number
  monthly_best: boolean
  tiles: string[]
  scene_id: string
  kind: CompositeKind
  bands?: string[]
  index?: CompositeIndex
  stretch_pct?: number[]
}

export interface CompositeResult {
  extent: Bounds
  overlay_uri: string
  raster_tif?: string
  meta?: Record<string, unknown>
}

export interface CompositionOverlay {
  /** Client session id — stable key for the overlay gallery. */
  id: string
  overlay_uri: string
  extent: Bounds
  opacity: number
  /** Short telemetry line, e.g. "Agriculture · B11-B08-B02" */
  label?: string
  /** Display name, e.g. "Agriculture" or "NDVI" */
  title?: string
  description?: string
  kind?: CompositeKind
  bands?: [string, string, string]
  index?: CompositeIndex
  presetId?: string
  /** Scene acquisition date captured at apply time. */
  sceneDate?: string
  /** Local GeoTIFF path for export (when available). */
  raster_tif?: string
  /** The run this was made under; empty for a project-level composition. */
  runId?: string
  /**
   * The area it was made over. What lets the board list every composition of
   * an area that has no run, instead of only the one on the map.
   */
  areaId?: string
}

export type WaterIndex = "NDWI" | "MNDWI" | "AWEI"

export interface WaterDate {
  date: string
  scene_id: string
  cloud_cover: number
  /**
   * AOI pixels actually observed on this date. Water fractions are a percentage
   * of this, not of the whole AOI, so a partly clouded date is not read as dry.
   */
  observed_pixels: number
  threshold_fixed: number
  threshold_otsu: number
  /** The Otsu value hit an empirical bound and is a bound, not an estimate. */
  threshold_clipped: boolean
  /** Too few observations to threshold at all. */
  threshold_degenerate: boolean
  water_fraction_pct: number
  water_fraction_otsu_pct: number
  water_pixels: number
  area_ha: number
}

export interface WaterAnalysis {
  /**
   * The row this run was recorded as, or absent where it was not recorded.
   *
   * The Go side withdraws its claim to have saved by returning nothing, so the
   * absence of this is the withdrawal. Anything telling the reader the run was
   * saved has to read it.
   */
  run_id?: string
  index: WaterIndex
  threshold_method: string
  threshold_fixed: number
  otsu_clip: number[]
  n_dates: number
  date_range: string[]
  aoi_pixels: number
  aoi_area_ha: number
  series: WaterDate[]
  peak_date: string
  peak_water_fraction_pct: number
  /** Water on some dates but not most: the flood signal rather than a pond. */
  ephemeral_pixels: number
  ephemeral_area_ha: number
  persistent_pixels: number
  persistent_area_ha: number
  mean_anomaly: number
  /** Occurrence raster as a data URI, coloured on a fixed 0 to 1 scale. */
  occurrence_uri: string
  extent: Bounds
}

export interface WaterRequest {
  polygon_geojson: GeoJSONGeometry | null
  start: string
  end: string
  max_cloud: number
  monthly_best: boolean
  index: WaterIndex
  label?: string
  run_label?: string
  project_id?: string
  /** The area this run is of, so the board can link the two. */
  area_id?: string
}

/**
 * Request for the flood envelope.
 *
 * The optional fields are absent rather than zero when they are not being
 * set: the sidecar reads a missing key as "choose the default", and 0 is a
 * legitimate request for three of them -- a reference threshold of 0 m asks
 * for the drainage surface itself, a buffer of 0 m for exactly the AOI, an
 * inset margin of 0 cells for no inset ring. Sending a default as an
 * explicit 0 asks for a different analysis than the one intended.
 */
export interface FloodRequest {
  polygon_geojson: GeoJSONGeometry | null
  /**
   * The products to compare, by DEM collection id. Absent selects the
   * four-product default set. Fewer than two the sidecar refuses: one product
   * yields an extent with no measure of how much of it that product chose,
   * which is the shape this analysis exists not to ship.
   */
  dem_ids?: string[]
  /** HAND thresholds in metres to sweep. Absent selects the study's sweep. */
  thresholds_m?: number[]
  /** Where the agreement raster is built. Need not appear in thresholds_m. */
  reference_threshold_m?: number
  /** Contributing area above which a cell counts as drainage. Zero is refused. */
  drainage_km2?: number
  /** How far beyond the AOI to read each DEM, so inflowing drainage is real terrain. */
  buffer_m?: number
  /**
   * Ring cut from inside the AOI polygon for the inset statistics.
   *
   * The key is inset_margin_cells and not the edge_margin_cells this once
   * sent: the ring used to come off the computed window, it now comes off the
   * AOI, and the sidecar refuses the old key by name rather than accept a
   * number that would describe a different ring than the one reported back.
   */
  inset_margin_cells?: number
  label?: string
  run_label?: string
  project_id?: string
  /** The area this run is of, so the board can link the two. */
  area_id?: string
}

/**
 * Ground size of one grid cell in metres, at the centre latitude of the
 * window. Every area in this analysis is a cell count times this, so it is not
 * a projected-area calculation and the two differ across the window.
 */
export interface FloodCellSize {
  x: number
  y: number
}

/**
 * The window the terrain chain ran on, which is provenance and NOT the extent
 * anything is reported over.
 *
 * This is the AOI plus FloodAnalysis.buffer_m on each side, less the border
 * cells trimmed to a rectangle every product covers. Nothing in this payload
 * is measured over it -- FloodAOI is what every count, area and index covers
 * -- and `bounds` places FloodAnalysis.agreement_tif alone, never the PNG. In
 * the recorded payload it is 43848 cells against the AOI's 5256, so a figure
 * read against these cells overstates the ground it describes by 8.3 times:
 * that reading is how a 4.5 km2 AOI came to be reported as 37.5 km2 of
 * classified land.
 */
export interface FloodGrid {
  width: number
  height: number
  bounds: Bounds
}

/**
 * The ground every figure in this payload is measured over: the cells whose
 * centre falls inside the AOI polygon.
 *
 * It carries the computed window beside itself because either number alone
 * misleads. `area_km2` alone hides that the terrain was solved over more
 * ground than is reported, which is what makes the areas trustworthy;
 * `window_area_km2` alone is the figure that used to be on screen. A cell is
 * in or out by its centre, so `area_km2` and the polygon's own area differ by
 * at most a half cell along the boundary.
 */
export interface FloodAOI {
  cells: number
  area_km2: number
  /**
   * Cells left after FloodAnalysis.inset_margin_cells is cut from the polygon,
   * which is the denominator of every inset index.
   */
  inset_cells: number
  /** The buffered window the chain ran over, as cells and as ground. */
  window_cells: number
  window_area_km2: number
  /** AOI cells over window cells: how much of what was solved is reported. */
  frac_of_window: number
}

/**
 * One DEM product's extent at the reference threshold, counted inside the AOI
 * polygon. `area_frac` is of FloodAOI.cells and not of the window, so it is a
 * share of the ground the reader drew.
 */
export interface FloodProduct {
  id: string
  collection: string
  /**
   * Nullable because null here means the fact was not recorded, not that the
   * resolution is 0 m or that the product was left on its own grid. Read as a
   * plain number and boolean, a null prints as a measurement that was never
   * made -- and `resampled` is the one column separating a terrain difference
   * from a resampling artefact.
   */
  native_resolution_m: number | null
  resampled: boolean | null
  cells: number
  area_km2: number
  area_frac: number
}

/**
 * The agreement count raster summarised. Unanimous cells are where the terrain
 * decides the extent; contested cells are where the choice of DEM decides it.
 */
export interface FloodAgreement {
  /**
   * AOI cells at each agreement level, indexed by how many products call the
   * cell flooded, so it carries one entry more than there are products and
   * sums to FloodAOI.cells -- not to grid.width times grid.height.
   *
   * counts[0] closes that accounting and is not a level of agreement: that no
   * product calls a cell flooded says nothing about how far the products agree
   * with each other, and a legend listing it as a class beside the others
   * flattens the one distinction this analysis draws. It is
   * unanimous_dry_km2, the dry remainder of the AOI, and the raster leaves
   * those cells transparent.
   */
  counts: number[]
  unanimous_wet_km2: number
  contested_km2: number
  unanimous_dry_km2: number
  /**
   * contested / (contested + unanimous wet). Null when no product calls
   * anything wet: there is no extent to take a share of, and rendering the
   * null as 0 would state perfect agreement over an AOI nobody called flooded.
   */
  contested_frac_of_wet: number | null
}

/**
 * Two products compared at one threshold.
 *
 * iou is the Jaccard index between the two binary extents. For a binary mask it
 * is numerically the critical success index (CSI) of the flood literature, and
 * a reader from hydrology looks for that name rather than this one.
 */
export interface FloodPair {
  dem_a: string
  dem_b: string
  threshold_m: number
  /**
   * Null when both extents are empty: the index is undefined over an empty
   * union, and 0 would state total disagreement between two products that
   * agree the AOI is dry.
   */
  iou: number | null
  /**
   * The same over the AOI shrunk by FloodAnalysis.inset_margin_cells. The ring
   * is cut from the polygon and not from the computed window, which the buffer
   * already puts outside every figure here. What it tests is unchanged:
   * whatever drains in from beyond the buffer is missing for the cells nearest
   * the AOI boundary first, so there HAND reads high and the extent small, and
   * a large gap from iou says the disagreement sits at the edge of the
   * reported area rather than through the middle of it.
   */
  iou_inset: number | null
  /**
   * Null when dem_a has no wet cell at this threshold, rather than a ratio over
   * a denominator of one cell, which would report that fact as 1.0.
   */
  area_ratio_b_over_a: number | null
  /**
   * Whether either side was moved onto the shared grid before its terrain chain
   * ran. True rows carry a resampling component alongside the terrain
   * difference, of the size quantified in FloodAssumptions.chain_grid; only the
   * false rows compare terrain alone. Null means the fact was not recorded,
   * which is not the same as false.
   */
  resampled: boolean | null
}

/**
 * The range the products span at one threshold: the narrowest and widest
 * pairwise agreement. Null throughout when no pair yielded a defined index.
 */
export interface FloodEnvelopeRow {
  threshold_m: number
  iou_min: number | null
  iou_max: number | null
  iou_min_inset: number | null
  iou_max_inset: number | null
}

/**
 * Every default the figures rest on, where it came from, and what is left out.
 * Prose written by the sidecar and carried verbatim; each entry names a choice
 * and states what moves if it changes.
 */
export interface FloodAssumptions {
  drainage_threshold: string
  reference_threshold: string
  thresholds: string
  /**
   * Which cells the figures are taken over, in the numbers of this run: the
   * AOI against the buffered window the chain solved. It travels with any area
   * quoted from this payload, because an area is a figure a reader attributes
   * to ground and this names which ground.
   */
  reporting_extent: string
  inset_margin: string
  cell_size: string
  alignment: string
  buffer: string
  /**
   * Which raster covers what. The GeoTIFF is the whole computed window and the
   * PNG is the AOI clip, so the two are not the same picture and a reader who
   * takes the GeoTIFF into a GIS sees ground no figure here describes.
   */
  rasters: string
  /**
   * The order the chain ran in and its measured cost: every product ran HAND on
   * the shared grid, so a coarser product was resampled before the chain rather
   * than after, and the two orders agreed at IoU 0.47 for the 90 m product
   * against 0.95 for a 30 m one over one window (n=1). That is the size of the
   * disagreement this analysis exists to report, so this string has to travel
   * wherever a resampled pair's figure does.
   */
  chain_grid: string
  excluded: string[]
}

/**
 * A HAND flood extent and the disagreement between the DEM products it can be
 * derived from.
 *
 * The envelope is TERRA's own measurement over the products it reads from
 * Microsoft Planetary Computer. It is not the range published by the study this
 * ports, which measured a different product set from a different catalogue;
 * quoting that range beside these figures would attribute someone else's
 * measurement to this map. `qualifier` carries the sentence that must travel
 * with any figure taken from here, so nothing should render a number from this
 * block without a route to it.
 *
 * Every array field is non-nullable: the Go side normalises each nil slice to
 * an empty one on the live path and again on restore, which is what makes that
 * safe here.
 */
export interface FloodAnalysis {
  /**
   * The row this run was recorded as, or absent where it was not recorded.
   *
   * The Go side withdraws its claim to have saved by returning nothing, so the
   * absence of this is the withdrawal. It read as absent on every run of this
   * product until the Go side began stamping it: the field was declared there
   * and never written, so the studio's live area reported the sentinel
   * "current" and could not record the run it was showing.
   */
  run_id?: string
  reference_threshold_m: number
  thresholds_m: number[]
  drainage_km2: number
  cell_size_m: FloodCellSize
  /** Provenance: the window the chain ran on. `aoi` is what the figures cover. */
  grid: FloodGrid
  buffer_m: number
  aoi: FloodAOI
  products: FloodProduct[]
  agreement: FloodAgreement
  pairs: FloodPair[]
  envelope: FloodEnvelopeRow[]
  inset_margin_cells: number
  qualifier: string
  assumptions: FloodAssumptions
  /**
   * The agreement counts as a single-band GeoTIFF, georeferenced on exactly
   * grid.bounds -- the whole computed window, buffer included. A path on the
   * machine that ran the analysis, not something the webview can open: it is
   * what a reader takes into a GIS, and the interface can only name it.
   */
  agreement_tif: string
  /**
   * The same counts rendered for display, clipped to the AOI bounding box with
   * every cell outside the polygon transparent, so the overlay covers what the
   * figures cover. Also a server-side path.
   */
  agreement_png: string
  /**
   * Where agreement_png goes on the map: the bounds of that clipped image
   * ALONE. grid.bounds is the buffered window, and placing the clip on it
   * stretches the overlay over several times the ground it covers -- the same
   * mistake in pixels that reporting over the window was in numbers. Same
   * field shape as WaterAnalysis.extent, so one placement path serves both.
   */
  extent: Bounds
  /**
   * agreement_png as a data URI, which is how every raster this program draws
   * reaches the webview. Empty or absent when the rendering could not be read,
   * in which case the numbers still stand and only the map is missing.
   */
  agreement_uri?: string
  /**
   * The same crop carrying the COUNTS rather than their colours, as a data
   * URI: the count in the red channel, one per byte, alpha marking the
   * reporting mask.
   *
   * It exists so the map can colour the raster from an expression rather than
   * draw a finished image -- agreement_uri's palette, and which counts it
   * draws at all, were decided in the sidecar. Absent when the file could not
   * be read, in which case the map draws agreement_uri and only the palette
   * control is missing.
   */
  agreement_values_uri?: string
  agreement_values_png?: string
}
